### ISSUE TITLE
fMSX core is outdated

### ISSUE THREAD

**Issue by gingerbeardman** [KMFDManic/NESC-SNESC-Modifications#1]
In June 2017 I submitted some changes to the fMSX core that updated it to 4.9 and also add more configuration: RAM, VRAM and more: https://github.com/libretro/fmsx-libretro/pulls?utf8=✓&q=is%3Aclosed%20is%3Apr%20author%3Agingerbeardman%20

Is it possible those could be integrated here by you building using the latest source?

**Comment by gingerbeardman** [comment]
The FMSX core has been updated elsewhere: https://github.com/pcm720/retroarch-clover-extra/issues/18#issuecomment-336860343

**Comment by KMFDManic** [comment]
Some Cores I didn't worry as much about Updating due to certain issues they gain in the Update.  For NESC/SNESC, Updated FMSX Core needs controls (controller), picked upon every exit to gui and reentry into another game.  The version I have kept was the last one to not have that issue.  You can select controller, and it sticks.  Every version after that, controller is lost upon exiting a game.  I can keep it in my extras and dependencies folder, however.

**Comment by KMFDManic** [comment]
Updated it into my Main Release Zip, in Dependencies & Extras Folder.  Thanks for the heads up on the extra changes that help towards compatibility!

**Comment by gingerbeardman** [comment]
Thanks for the info! 

I'll look to fix the "losing controller" issue if I can

**Comment by gingerbeardman** [comment]
I was thinking, it is quite possible and easy to backport the default configuration and RAM/VRAM config options to 3.9 I can help if required

**Comment by KMFDManic** [comment]
I am glad to find others are interested in this excellent Core that I have been playing around with for quite some time!  On the NES & SNES Classics, several Cores have nuances to adjust to due to their special environment.  NX Engine, with recent Core Updates, moved the save location, which broke save ability on NESC/SNESC.  A few other specific Cores, not many, mind you!...have similar conflicts of interest.  I will do a little more testing with the latest Update you recommended me to get onto my Github!  And, I will think about the best way to proceed as far as fixing the controller issue.  It may be a very trivial thing, indeed, and not really require much effort to resolve!  I have already jumped onto Commodore 64 with its lack of keybinds, and the great guys who work with that Core, helped implement keybinding!, like so...

NESC/SNESC: Commodore 64 Keybinding

https://www.youtube.com/watch?v=dBn9MkHUA_E

And, of course, I have also done FMSX Videos:)

NESC MSX Test Part 1: 

https://www.youtube.com/watch?v=w0F2JlFHn4I

NESC MSX Test Part 2: 

https://www.youtube.com/watch?v=nL1ToAUmcSM

Thanks again for your input!  I would love to see compatibility progression with more optimal controls that stick:)

**Comment by gingerbeardman** [comment]
Great! I'll leave it with you, do let me know if I can help with anything

**Comment by KMFDManic** [comment]
Will keep updated FMSX in Main Set.  To keep controller from being lost, Quick Menu, Save Core Override must be used.  Once activated, system can be powered off and back on, and Controller still works.  Issue Closed, will update this into main set shortly:)  Now for the Sram issue with PicoDrive!

**Comment by gingerbeardman** [comment]
Sweet!
