### ISSUE TITLE
PSP > "Tactics Ogre - Let Us Cling Together" > can't enter name / low performance

### ISSUE THREAD

**Issue by Nifty79** [KMFDManic/NESC-SNESC-Modifications#103]
### Step 1: Describe your setup:

  * hakchi2 CE version: 1.1.0
  * retroarch used (filename): km_RetroArch Xtreme (3-22-18)
  * hmod(s) used by the game you are having problens with (filenames): km_PPSSPP Neo (3-13-18)
  
### Step 2: Describe the problem:
  
  * I just get a white screen after the game prompts to enter my player name. So I can't begin to play. And the performance is generally very low, even with frame skip. 
  
Do you know of any way to make the game work?

Regards

**Comment by KMFDManic** [comment]
I would need to personally test this game.  But, have you seen any of my PSP Performance Upgrade Videos?  And, have you installed the PSP Xtreme Add-On?  This helps with many CPU intensive games, such as Ultimate Ghosts N'Goblins, Racing Games, etc.  You may want to try, in Core Options, toggling Block Transfer GPU, then restarting, Resuming.   Some Games can have issues due to Block Transfer being on and or off.  But, MOST Games function fine with it on.  I had to find a standard to stick with for best compatibility.  I tested hundreds of games, and the settings I used worked best for most of them.

**Comment by Nifty79** [comment]
Yes, meanwhile I have watched your PSP Performance Videos, played with various settings - including toggling Block Transfer, and installed the PSP Xtreme Add-On. 

Sadly I still can't get past the blank white screen, after being prompted for my player name. 

But, I understand that you needed to find a middle ground. Your works still enables people to play a vast amount of games. As far as I am concerned, I think am going to treat this bug as a known issue. ;-)

**Comment by KMFDManic** [comment]
You did restart after applying change after change?  There is ONE other possibility.  What if you attempted to use a Save State, and loaded it?  Maybe, you have a shot at the game.  It has worked for other games.  I did a video about how to do this, of course:)

https://www.youtube.com/watch?v=qmZ2c5_l5GM&t=115s

**Comment by KMFDManic** [comment]
Since this is technically something that is about compatibility, rather than something we can truly fix, I am closing the issue.  I really wished the game worked the way you wanted it to, though!  Excellent game!  But, check into the save state exploit, if you get a chance.  This sort of exploit will be something I cover in another video:)
