### ISSUE TITLE
EEPROM/Soft DIP settings not sticking after Retroarch exit

### ISSUE THREAD

**Issue by zweifuss** [KMFDManic/NESC-SNESC-Modifications#115]
### Step 1: Describe your setup:

  * hakchi2 CE version: 1.2.2
  * retroarch used (filename): RetroArch Neo 1.7.2a
  * hmod(s) used by the game you are having problens with (filenames): external Retroarch, FBA2016, Mame2003
  
### Step 2: Describe the problem:
  
  * I have this really weird issue you may be able to help me with. I can't save any of the EEPROM settings in arcade games (I use Mame2003 and FBA2016, latest ones). I am using the USB-HOST external cores HMOD. So say for example the soft setting of Neogeo (using FBA2016)... I go in, change everything, play my game, exit retroarch, and then when I go back into the game, everything is at factory again. Or if I play MK2 (Mame2003), I go into the menu and increase the sound volume, save settings, go out of retroarch, come back in, it's all back to factory again. I tried going into retroarch and changing folders, but even that doesn't stick. When I go back into retroarch again (same core), and check the settings, they're all back to normal again. The only thing that seems to save fine is my key maps. So I may be misssing something obvious or these emulators don't have that feature in them for this particular device. Cause I know with the retropie, this was never an issue. For example I would set my SFiii2 into widescreen, change to freeplay, etc., and when I would play it again a few days later, everything was saved and I didn't have to go back and change all my settings again.
  
### Notes: Are you in the right place?

  * For issues or feature requests related to hakchi2CE goto [TeamShinkansen/hakchi2/issues](https://github.com/TeamShinkansen/hakchi2/issues) and file a Github issue.
  * For general usage questions, post a question on [Reddit](https://www.reddit.com/user/MDFMKanic/) or the [Nintendo Classics Discord](https://discord.me/page/nintendoclassics).

**Comment by KMFDManic** [comment]
This is a bit of a double edged sword.  In my own personal tests, goofing up MAME controls or a dip setting, etc, and having it stick can be a bit irritating if you want it to be able to revert back to default.  We can technically make things so they stick.  But, the problem is, a lot of people will accidentally screw up, then not even reinstalling RetroArch will be able to default the stuck settings.  They would need to use special means to remove the stuck dip switches, etc, via FTP.  This is especially important to me, when I am messing with MAME 2003.  I love the safety net of being able to reconfigure any controls, and knowing powering down the system will default them, again.  It is something I pondered having.  But, I think the majority would appreciate the safeguard of not being able to screw up RetroArch by changing the wrong thing.  Even normal RetroArch, if you go to RetroArch, controls, then reconfigure, mess up, you can reinstall RetroArch to fix that.  But, dip switches, etc, reinstallation of RetroArch would still retain those settings, and not everyone is adept as using an FTP.  There are other ways of defaulting, but not necessarily user friendly.

A slightly tricky scenario, simply due to the repercussions of screwing up controls, basically.  This still doesn't mean I won't consider it as an option.

**Comment by zweifuss** [comment]
OK Thanks for the concise answer. I can wait until later. Nobody seems to be requesting it. Glad to know you know what I mean though, I'm not sure I used the correct terminology. Thanks again for your tireless efforts, look forward to the next release!

**Comment by KMFDManic** [comment]
I am going to push this as an Update this week, Dip Switches, saving.  Should be out by the weekend, if all works out ok.

**Comment by zweifuss** [comment]
Cool thanks! Really appreciate your work.
