### ISSUE TITLE
PSX In the Hunt convertion?!

### ISSUE THREAD

**Issue by AntiFly** [KMFDManic/NESC-SNESC-Modifications#118]
### Step 1: Describe your setup:

  * hakchi2 CE version: 1.2.2
  * retroarch used (filename): xtreme
  * hmod(s) used by the game you are having problens with (filenames): KMFDManic-NESC-SNESC-Cores.4-28-18 same behavior on the KMFDManic-NESC-SNESC-Cores.4-21-18
* Used CORE: PCSX
  
Hi dude,

i followed your [Tutorial](https://www.youtube.com/watch?v=RRjyl4GY09U)
but unfortunally the game does not start. retroarch tries loading and fall back to game selection menu.
is there anything i could check or do to get in run?

ive tried to convert it now three times but wont get it to run, can you confirm that this game still works converted to *.pbp with pcsx.1.7.1?

i just loaded up the .cue file from the bin file i created and this works well for me. but pbp is more convinient. so would prefer to use that one ;)

cheers

**Comment by KMFDManic** [comment]
What is the full Command Line for the converted Eboot, from beginning to end?  NOTE: You may want to run the Arcade Version using MAME 2003 Xtreme in my set.  It has been fixed for a couple months now:)

https://www.youtube.com/watch?v=KZRH9ozDMcc

But, keep me posted, otherwise:)  One of the very best SHMUPS, ever:)

Thanks for your support and continual feedback!  It is greatly appreciated!

**Comment by AntiFly** [comment]
hey thanks for the info about mame i give it a shot.
but hey my cue/bin is working well, so what could ive done wrong in using PopstationGUI? theres not much do wrong here isnt it ? (ive used compression level 9, rest of the settings left alone)

**Comment by AntiFly** [comment]
this is really weird, ive now tried just your popstation version and this one worked, ive got mine which is "same version"...
 strange... whatsoever its working now. 
cheers

**Comment by AntiFly** [comment]
got it to work ;)
