### ISSUE TITLE
REQ | MAME 2014 xtreme KMFDManic Edition

### ISSUE THREAD

**Issue by AntiFly** [KMFDManic/NESC-SNESC-Modifications#120]
Hi Dude,

ive tried some of my favorites games but unfortunally they are not available for MAME 2003 so ive tried it for MAME 2014. Its really sad, none of them worked well for this CORE.
Could you do some optimations to that CORE too like the 2003 that we can at least play them ?

List:
Great Game von MAME 2014 (0.159) that are not available in MAME 2003 (0.78)

- [ Blazing Lazers
Deathsmiles (CAVE)
Deathsmiles II (CAVE)
Denjin Makai
DoDonPachi DaiFukkatsu
DoDonPach II: Bee Storm
ESP Galuda II (CAVE)
Gekirindan
Giga Wing 2 (CPS2)
Hyper Duel
Ibara (CAVE)
Ibara Kuro Black Label (CAVE)
Muchi Muchi Pork! (CAVE)
Mushihimesama (CAVE)
Mushihimesama Futuri v1.5 (CAVE)
Pink Sweets: Ibara Sorekara (CAVE)
Radian Silvergun
Raiden Fighters
Raiden Fighters 2
Raiden Fighters Jet
Slamander 2
Shooting Love 2007
Viper Phase
-------------
With CHG
-------------
Border Down
Chaos Field
Ikaruga
Karous
Radilgy
Shikigami No Shiro II
Trigger Heart Exelica
Under Defeat] 

cheers

**Comment by KMFDManic** [comment]
Some of the ones you mentioned, are not supported in any MAME from 2003-2014.  But, some like Salamander 2, require Konami GX Bios, in order to function.  Salamander 2 runs fine on MAME 2003:)  It also runs great with the PSP Salamander Collection!  Denjin Makai, changes to help other Banpresto Games, were added into MAME 2003 in my set, last year.  This may potentially work, as well.  I would need to retest.

Several you mention, even if they did function, would run at about 5-11 FPS, at the most, including Radiant Silvergun/Ikaruga

Blazing Lazers does work, it is called Gunhed:)

Great taste in SHMUPS!  We can adjust this list, to reflect some Compatibility.  But, in Xtras/Arcade, check out the compatibility lists I have added for some of the Cores!  And, you really need to try some of the later ones, via FBA 2012/FBA 2016.  They will function better:)

My SHMUP 'Stravaganza Video Series, I showcased several Cave SHMUPS in part 1:)

**Comment by AntiFly** [comment]
thanks for relying to this :)
ye ive tried every single on this list and i guess 2 worked very slow, one was loading but unplayable at this speed. to be honest, playing shmups in 10fps is like pain in the ass xD.

so coming up to the salamander and banpresto, do you mean that i can smash the bios from the mame2014 in and load up the game through mame2003?
same with Denjin Makai?

> Blazing Lazers does work, it is called Gunhed:)
so whats the zip name , could you tell me? i do not find this either in mame2003 (??) nor in mame2014 (blazlaz.zip)
Ive tested it within fast PCE , this works.

> Great taste in SHMUPS! We can adjust this list, to reflect some Compatibility. But, in Xtras/Arcade, check out the compatibility lists I have added for some of the Cores! And, you really need to try some of the later ones, via FBA 2012/FBA 2016. They will function better:)
well, thanks ;)
ive checked them cross through fa2016, they are not available in v0.2.97.39 (so far i can tell).

I watched some of your vids, great work dude. Im into using such information and find my "own" way what suits my needs.

i will have a look into your compat list you mentioned about.
cheers

**Comment by AntiFly** [comment]
ok found slamander 2 , denjin makai , denjin makai 2 (Guardians)... for mame 2003 ;-)
