### ISSUE TITLE
Highscore for the 1.7.3 CORE?

### ISSUE THREAD

**Issue by AntiFly** [KMFDManic/NESC-SNESC-Modifications#123]
Hi Dude,

great job on the latest Update i installed it right away ;)
so im a bit confused about these different cores, why 3 coresets of Retroarch 1.71 , 1.72 and 1.73.
i just installed the 1.73 because its the newest one.. whats your olympic goal to have the old ones still inside the package? i didnt get it.

if you have them for archive , just for the old input, why not put them in the _xtras folder and keep on in a clean structure youve build recently.. dont get me wrong i dont want to complain about that its just confusing to me.

are the xtreme settings in all cores the same, is highscore available in 1.73 or just in 1.72?

**Comment by KMFDManic** [comment]
@AntiFly Many things can be confusing about an "Open World" set:)  But, I can clarify things for you on anything you have difficulties with.  Many HATE 1.7.2 and on because the Inputs they have saved to mapper files will not work with them.  Some have reprogrammed hundreds of games!  Essentially, I leave 1.7.1 for these people, as well as the FFMPEG Video Support.  Not everyone will like or want to use 1.7.3!  You can use just 1.7.1 if you'd like and be absolutely fine:)

The hi-score, requires a few things, Install MAME 2003 Hi Score, RetroArch Hi Score Add On, as well as run the games from the main UI with /bin/mame2003-hi-score  Not all games will work:)  But, many many do, and it is awesome!  Try out Fantasy Zone, 1942, etc.  

By the way, the music you linked me to, I was unable to download due to size limits.  You are welcome to message me on Reddit, under the name MDFMKanic if you want me to share it for next Release!  

Thanks so much for your input!  I am absolutely glad to help you understand things when using my set:)

@gingerbeardman Respect:)  Exceptional work on Canoe Deconstruction:)  Enjoy 1.7.3!  Be sure to fill me in on any run ahead settings you deem worthwhile for lag latency adjustments!  I can adapt them to the "standard release" and have it be lag input oriented!

**Comment by AntiFly** [comment]
@KMFDManic 
thank you for explanation, please give it another try to download i removed that limit on that hoster. gimme feedback if this worked for you ;)

**Comment by KMFDManic** [comment]
It would not let me download, unfortunately.  Every time it counted down 10 seconds, then allow a download, it started counting down again.  It was a bit funny, haha.  We can certainly make things next Update:)

**Comment by AntiFly** [comment]
I will upload to mega later on this day. ;)

Von meinem iPhone gesendet

**Comment by AntiFly** [comment]
there you go , try this one ;)
[MUSIC](https://mega.nz/#!4pJWWQwA!PmDgHokK_R6hME4_Vb4Gipovvu0LSlvJBdhxwRbWDC4)

**Comment by KMFDManic** [comment]
@AntiFly German is your native language?  I was able to get the music.  Thanks.

**Comment by AntiFly** [comment]
Hi kmfdmanic,
Yep why? ;)

Von meinem iPhone gesendet

**Comment by KMFDManic** [comment]
@AntiFly Sent from my Iphone didn't give it away or anything:)  Last thing, before I close this issue.  The music you shared with me, is any of it copyrighted, or free to distribute, as long as properly credited?  I will respond, despite issue being closed:)

**Comment by AntiFly** [comment]
Except the three mario which was provided through the mod creator itdelf everything is from cracking groups or keygen groups so there is no copyright where i know of. The filenames are related to the origin creator group and are untouched, i just converted them as of compatibility to the hmod.

Von meinem iPhone gesendet

**Comment by AntiFly** [comment]
Do you like it too?

Von meinem iPhone gesendet
