### ISSUE TITLE
Not an issue but can't post in requeats

### ISSUE THREAD

**Issue by DecanFrost** [KMFDManic/NESC-SNESC-Modifications#131]
Hello... wanted first say great work.  Love it all.. watched all your videos and they are great too.

I had a thought for a project you can do if you.  Port hakchi2 to Xbox.. instead of individual emulators and coinops maybe we can make a hakchi2 theme skin for retroarxh that is already on original xbox,  update the cores and import the games the same way with the same layout as the SNES mini menu system.

**Comment by KMFDManic** [comment]
The problem here is that Hakchi 2 uses Windows Operating System as a Dependency, amongst other things.  The best you can really do is have some clever Themes for XBOX RetroArch, such as how the Mini NES was done on PC:)  Use what is already there, and do your best to replicate for a fun gimmick.  It would be far more likely, yet still not very high priority, to see Hakchi2 Ported to Mac Computers, before an Xbox.  Fun idea, however:)  It just isn't quite feasible, for now.  Thanks for the praise on the videos!  I just posted another Update!
