### ISSUE TITLE
Query regarding uninstalling Retroarch to install a newer version?

### ISSUE THREAD

**Issue by bolton80** [KMFDManic/NESC-SNESC-Modifications#134]
### Step 1: Describe your setup:

  * hakchi2 CE version: 1.2.5
  * retroarch used (filename): _km_retroarch_172_xtreme_6_19_18
  * hmod(s) used by the game you are having problems with (filenames): N/A
  
### Step 2: Describe the problem:
  
  Sorry to ask here, I'm not sure this is the right place, but could you please confirm the correct way to uninstall an old version of Retroarch and install a new one? I know how to delete a core from within Retroarch when it is running, but I'm not sure whether I am updating Retroarch itself correctly. I use the dtm_external_retroarch_5_12_18 mod (so it's on my USB stick) if that makes a difference?
  
### Notes: Are you in the right place?

  * For issues or feature requests related to hakchi2CE goto [TeamShinkansen/hakchi2/issues](https://github.com/TeamShinkansen/hakchi2/issues) and file a Github issue.
  * For general usage questions, post a question on [Reddit](https://www.reddit.com/user/MDFMKanic/) or the [Nintendo Classics Discord](https://discord.me/page/nintendoclassics).

**Comment by AntiFly** [comment]
You would be good to reset snes mini and install all desired hmods afterwards.

Von meinem iPhone gesendet

**Comment by KMFDManic** [comment]
@bolton80 There are several ways to do it.  But, generally, I do a from scratch set-up when I am Updating Cores to avoid any issues.  That way would be to delete the entire libretro Folder.  THEN, I would do install/repair/custom kernel option on Hakchi2 CE, and then reinstall HMODS to NAND and/or External RetroArch.  If you try it other ways, you can unintentionally run into conflicts and have weird loading, crashes, freezes, etc due to improperly uninstalling before Updating.  BUT, depending on WHICH Core/RetroArch you were previously on, you can sometimes simply just install and not uninstall!  I would need specifics.  But, if you went from NEO to mine, you would need to delete Libretro.  If you went from my "Recent" ones to my "Current" ones, you can simply install and it wouldn't necessarily conflict.  Again, I prefer things from scratch, since it never fails:)

Keep me posted, if you have any other questions!

@AntiFly Reset will not be good to use if running External RetroArch.  But, it is great for NAND HMOD Installs:)  Thanks for helping out!
