### ISSUE TITLE
Retroarch Xtreme gives C7 error on all SNES games from USB

### ISSUE THREAD

**Issue by agufungus** [KMFDManic/NESC-SNESC-Modifications#142]
### Step 1: Describe your setup:

  * hakchi2 CE version: 3.4.1
  * retroarch used (filename): _km_retroarch_173_xtreme_netplay_8_22_18.hmod
  * hmod(s) used by the game you are having problens with (filenames): none
  
### Step 2: Describe the problem:
  
  * I just discovered a problem with _km_retroarch_173_xtreme_netplay_8_22_18.hmod: When I have it installed on my NES Classic with USB dual-boot, it always causes my SNES games from USB, both stock and added (all using Canoe), to give error C7. Is there a way to fix this, or do you recommend a previous version for the time being?

**Comment by KMFDManic** [comment]
This means you improperly uninstalled previous RetroArch, before installing new one, most likely.

Do kernel uninstall. Then install/repair kernel.  Then, reinstall RetroArch Xtreme 1.7.3 netplay, and test with an NES Game.
Command line beginning should be 
/bin/fceumm

Once successful, install other hmods you want from my set.  C7 means no destination target found.  You have traces of past installations, incorrect command line arguments, etc.

Keep me posted

**Comment by agufungus** [comment]
Thank you for the advice. I did use Hakchi CE to install the kernel, tiny7z and all. I also tried to remove all traces of past installations by selecting factory reset, and then reinstalling the custom kernel. The SNES games through Canoe do work properly when this version of Retroarch is not installed, but when it's installed, that's when the errors start. I uninstall the .hmod and the games work again. Then I tried installing other versions of Retroarch, and I get the same errors, too. I'm beginning to thing that there might be something in Hakchi2 CE that broke something in my NES Classic that can't be deleted with factory reset. I'll try to communicate with the developers to see what's going on.

**Comment by KMFDManic** [comment]
Those I have seen have this problem in the past has typically been due to a slow or not really good flash drive/OTG set-up.  And, of course, if you attempted to Dual Boot with NES/SNES, you can lead to problems yet again.  If you have a firewall/virus protection, they could be conflicting with Hakchi CE's ability to properly work with the kernel.  CE is fine for most people, until introducing conflicts such as bad or slow flash drives, virus protection, firewalls, and of course improperly set-up dual boots, amongst other things.  You using the Micro USB cable that came with the system?  And, what hardware do you have as far as flash drive and OTG?

**Comment by agufungus** [comment]
Yes, I'm using the USB cable that came with the system, for OTG I'm using [this](https://www.amazon.com/gp/product/B013ENUF0Y/), and [this](https://www.officedepot.com/a/products/723572/SanDisk-Cruzer-Glide-USB-20-Flash/) for USB drive. I tried reflashing  with antivirus off, and even a different USB drive (Sandisk Cruzer Switch 16GB), and the errors persist.

UPDATE: I finally found the cause of the problem! It was one of the Classic Pro Controllers what was causing the errors when Retroarch is installed. Fortunately, the error doesn't happen when it's in the second controller port. I might consider returning it and order a better working one online. Thanks for the help, anyway.

**Comment by danielacanela** [comment]
Hi, so I have the same issues everyone has and for the past 3 days it has been keeping me from sleeping O.O, so I have a nes classic, I got all the cores from RetroArch, I did step by step everything I needed to do in order to add all the cores. DONE.
now I got to the part of the roms
I dont know anything of what I am doing and I apologize if I sound too ignorant or boring to explain to.
So when I got to the part of the games, my issues started. 
I downloaded all the roms from known websites that I know ppl use all the time.
I changed the names, I put the zip folder into the game folder on Hakchi w the same ID number, so I know I did everything alright and still none of the 64 and SNES games work...

Please give me a website good enough so I can finally play. thanks
