### ISSUE TITLE
Reicast get Dolphin Blue to work ?

### ISSUE THREAD

**Issue by AntiFly** [KMFDManic/NESC-SNESC-Modifications#144]
### Step 1: Describe your setup:

  * hakchi2 CE version: 3.4.1
  * retroarch used (filename): KMFDManic-NESC-SNESC-Cores.9-3-18
  * hmod(s) used by the game you are having problens with (filenames): KMFDManic-NESC-SNESC-Cores.9-3-18
  
### Step 2: Describe the problem:
  Hi mate, ive watched your video about Atomiswave (great job again by the way).
I didn´t got blue dolphin wo work so far. ive placed the bios files correctly (as far i can tell).
ive tried to add dolphin.zip and the extracted .bin file and start it with /bin/reicast parameter but it just get black screen and fall back to snes menue...
youve talked alot of .gdi , .chd files but i guess thats just for dreamcast not for atomiswave.
so first question is which roms do exactly work for atomiswave they are not quite common ;-)
and second how to add exactly... extracted, .zip or do i need to convert them anyhow?

the dolphin.zip i have has a .bin and some .icx files inside... guess wrong rom??

if i add the game, reicast emulator is not shown on the available list. so guess it need to be implemented either.

cheers

//Edit:
ive found rom with .bin file format, but also not working...
situation is unlclear for me what to do , to get it run ?

//Edit 2:
ive tested my roms with NullDC r150

    Demolish Fist (working)
    Dolphin Blue (working)
    King of Fighters NeoWave (working)
    Metal Slug 6 (working)

**Comment by AntiFly** [comment]
Checksum check byte filesize to hexcode for .lst
https://www.binaryhexconverter.com/decimal-to-hex-converter

**Comment by AntiFly** [comment]
4 everyone lookin for the correct bios files, this might help (md5 checksums) ;-)
https://github.com/libretro/libretro-super/blob/master/dist/info/reicast_libretro.info

**Comment by AntiFly** [comment]
Reicast is showing me now all Bios "Firmware" files are present, i made sure the md5 has is correct...
i really dont know at the moment where the issue is.... i saw you captured the video through retroarch 1.3 , maybe its not working with 1.4 ??

**Comment by AntiFly** [comment]
Solfed it myself, man dude  what a mess, you could safed me hours of investigating why this is not working, this odyssey of mine can help anybody else to checkout this stuff "what can you make wrong at this" ^^

so the default recommendet bios is not working (hash) instead i found one which worked on pc and snes mini ! Filename: epr-21579d.ic27 with MD5 765bc6e3366d3d63593a59febb4acc53.

sound is really making me crazy with this stuttering... hope you find a way to tweak performance for us here *fingers-cross*

**Comment by KMFDManic** [comment]
Sorry, I was working, and didn't have a chance to help out or respond, as of yet.  I would have been able to sort your issue out very fast!  I appreciate the compatibility tests on the Atomiswave Games!  Props to you for your thoroughness!  Rumblefish Games working is a good thing, as they had issues in the past.  Demolish Fist, despite working, might not have "controls".  Note, some of these games may not have controls, whatsoever.  

For the record, the BIOS should overwrite existing data, if using /hakchi/transfer  If on Hakchi 3.4.1, you'd need to uninstall/reinstall, since it would register as already installed.  And, yes, some hash checksums that are recommended, are not always the ones that work out best, unfortunately!  

Ikaruga, unfortunately, will likely remain slow.  But, Many Many other games run a steady and very solid 30 FPS with the Performance Upgrades I have done!  Be sure to check out Drill, Hydro Thunder, Marvel Vs Capcom 2!  And, you are always welcome to email me!  I am very glad you put in this effort, as your test results are great!  We just need to confirm which games do or do not have controls properly hooked up!  You rock, as always @AntiFly Welcome to the wonderful world of testing, testing, testing:)  Never forget my email is always there for you, anytime!  I work a few double shifts throughout the week, so there are lull periods where I cannot properly respond for at least 10-14 hours at a time!  Keep in touch, man!  I will leave this Issue Open, for now, so we can address compatibility/control concerns!  I will post this compatibility for the Next Update.  And, of course, I will shout out to you for your hours of testing!  That is very much greatly appreciated, without a doubt!

So, last note, I will add a Compatibility File for Next Update, it will cover Naomi/Atomiswave/Dreamcast Games!  

Hope you are enjoying the Update/Core, as well as the ability to run Cores with far less NAND Space being used, my friend:)!

**Comment by KMFDManic** [comment]
@AntiFly Justme488 has started taking information from me, to help make necessary BIOS, etc, more convenient and easy to swallow.  Check out Xtras/BIOS, and the Advanced BIOS.pdf.  I think we can utilize that pdf to put in all the detailed BIOS Checksums necessary!  If you'd like, you can email me, and I will give you details on how we can pull that off.  The officially accepted ones, as we already established, will not always be the best way to go.  But, we can prioritize this, as I know this is something very irritating for you and many others!  I will even include the md5 tool, which I have used hundreds upon hundreds of times over the years!  I will be doing another double shift tonight.  But, this will be the next agenda, if that suits you!  I always welcome your feedback and adjustments that benefit the Core Set for the better!

**Comment by AntiFly** [comment]
@KMFDManic 
thanks for your input mate.
the information about the order on installing cores in special retroarch is a essential one.
if i remember right such information already exist for the ppssp core but i thought from the logicall thinking it would make sense, retro arch as a core and the others as "plugins" as you may say so.... i created this list for myself to remember the order. 
[_INSTALLED_MODULES.txt](https://github.com/KMFDManic/NESC-SNESC-Modifications/files/2358419/_INSTALLED_MODULES.txt)

I now will change the order of retroarch to the end of my install process, that would be your idea right?

Your idea to puth the MD5 sums into the bios pdf is great for everyone.. lets do so !

cheers :+1:

**Comment by KMFDManic** [comment]
And, @AntiFly , if you got to see the first Dreamcast Release, and, even the 2nd...The 3rd one (current), is far better!  I am very happy to be able to play dozens upon dozens of games fully, at 30 FPS!  We are working on finalizing the BIOS Guide, and you will have a testing credit in it, per my request.  If you do not mind, send me an email.  I would like to do compatibility comparisons with the Naomi Boot I am using, versus the one you are using.  Otherwise, all is excellent on my end, and ALL BIOS are covered and accounted for.  I just want to reaffirm which md5 I will go with for Naomi.  This will definitely go into next Update:)  We currently have only 3 Cores that are not yet functional (no success loading games).  These are Hatari, ScummVM, and Free2JME.  I will make sure these are notated, so people don't go crazy trying to run them.  They are there, just like I originally posted P-UAE, in case!  Amiga will certainly get better, as well!  Keep in touch!  I will look for your email, and this Guide will be completed over the weekend.  I will email you it back in a response so you can give your input.

**Comment by AntiFly** [comment]
@KMFDManic , 
I have some cores in use, you could see on my _INSTALLED_Modules.txt, so yeh I could double check some of them, no problem ;)
Unfortunally I dont have your e-mail , we correspondended just for the github mail. I suggest you got this as me in CC. So if you like correspondend to an old thread and we can exchange for that behavior ;)

ScummVM runs on my X360 fine, could give this a double check on snes mini in time...
I run the amiga, commodore etc.. consoles on my X360, i really dont want to check them on snes again, thats a nightmare get this running.

**Comment by KMFDManic** [comment]
@AntiFly You really shouldn't be having conflicts like that.  Are you trying to run these via NAND or External RetroArch?  It very much seems like you've maxed out your NAND by installing the database, which takes up a lot of space.  If you are breaking a Core, then installing another, and breaking another, that simply means you are using far too much NAND.  Custom Borders also takes up a lot of space.  So, essentially, from the get go...

Hakchi 3.4.1, Reset Kernel OR Uninstall Kernel, then Install/Repair Kernel

Then, install Master BIOS Module, along with primary Cores you want, such as Reicast, etc.  Be careful with Custom Borders and Database, since they are BIG HMODS!  Then, after these are installed, install RetroArch 1.7.4 Xtreme, by itself:)

Keep me posted!

**Comment by AntiFly** [comment]
@KMFDManic 
Ive tested some of my favorite games with the "recommended" bios.
So at least one of the error02 games from my former test was working, but its obsolete for me "Capcom_vs_SNK_Millenium_Fight_2000_Pro". 

Since the games im intrested in are working both the same I will stick with the bios ive discoverd working.


//my former test with that bios was just a bad one cause I guess youre right the nand was full. that drove me to look for a bios alternative which wasn´t really a need for, but fit in the end for me well.

**Comment by caretakerz** [comment]
Ok, so I found a bios with the same checksum.  Renamed it to naomi_boot.bin.  Placed it in the dc folder in master bios module.  Uninstalled everything, including kernel, and reinstalled them individually, with _km_retroarch_174_xtreme_9_3_18.hmod being last.  Checked rom file with .lst file, and they match.  Everything seems to be in order, but my game still won't boot at all.  It just kicks me back to the menu.  What am I doing wrong?  Is there a change in the command line that's necessary?  Should it be directed at the .bin file or .lst file?  I've tried both, but still......nothing.

**Comment by KMFDManic** [comment]
@caretakerz Make sure the lst file is NOT compressed.  And, also simplify the names of the bin or dat, then modify the lst to account for that.  I have dolphinblue.bin and dolphinblue.lst  Obviously, the name of the lst file won't matter, since it is essentially just a cue!  But, simplify the bin or dat, then modify the lst file to have exact same name, using notepad++  I have it in Xtras/Tools

**Comment by caretakerz** [comment]
I'll try that.  What about the command line?  Should it be /bin/reicast /var/games/CLV-I-FVBIO/dolphinblue.bin, or /bin/reicast /var/games/CLV-I-FVBIO/dolphinblue.lst?

**Comment by caretakerz** [comment]
HAAAAAAALELUJAAAAAAAAAHHHHH!!!  Finally got it!  MVC2 is very slow, though.  Simplifying the name of the files did the trick.  Going to try the games that are running better.  Thanks

**Comment by KMFDManic** [comment]
@caretakerz Dreamcast Version of Marvel Vs Capcom 2 runs fine:)

https://youtu.be/-mAfhwrdiiQ
