### ISSUE TITLE
advanced_music_hack.hmod gone ?

### ISSUE THREAD

**Issue by AntiFly** [KMFDManic/NESC-SNESC-Modifications#160]
Used: KMFDManic-NESC-SNESC-Cores.10-7-18.Xtreme

is the advanced_music_hack.hmod gone in the current set or is this by mistake.
couldn´t find a info about that in the release notes?...

I think ive remember that you talked about that this will be an upcoming feature or implemented into hackchi ce itself but it isnt right now ?... 
please clarify ^^ 

greets

**Comment by AntiFly** [comment]
youre welcome, i hope its positive critique ^^
so well yes my goal is help to have a clean and nice set indeed ;)

with the mouse driven game, not that i am aware of, i mean i have some point an click but no really mouse driven game. (indiana jones, zacmackracken...)

you may add the .ips of the thing ive send you last days to your set as you did for metro once.
cheers

**Comment by KMFDManic** [comment]
@AntiFly Due to how the Core Set will be read by Mod Hub in next CE Release, the default HMODS, such as Advanced Music Hack will be available two ways.  One, with CE download.  Two, I will keep back-up of the Package for CE inside Xtras/Hakchi.  Advanced Music Hack is one of the included HMODS, as mentioned.  So, you can grab it from 3.4.1 CE which is in my Xtras/Hakchi.  When CE updates, I will keep most current version backed up in same folder.

@bolton80 Might not be an easy fix to pinpoint on the mouse.  I will test Cannon Fodder.  I will recommend in Release Notes for next Release for people to primarily use P-UAE Normal Version for Mouse Driven games, and the 2 Player Mode Activate and such with P-UAE Xtreme.
