### ISSUE TITLE
Where's the source code?

### ISSUE THREAD

**Issue by missionfloyd** [KMFDManic/NESC-SNESC-Modifications#167]
This is all GPL-licensed. You really should be publishing the source code.

**Comment by KMFDManic** [comment]
I am well versed on the GPL licensing.  I do things, like they do with ingredients, list "all that might be contained",  I generally use the libreto source code, and remove commits that are not pertinent to our platforms, such as Nintendo Switch, etc.  I deem this the Butterfly Mod Effect, per my general Release Notes.  What might help one platform, might potentially hurt another.  Usually, when these issues are found, they are quickly resolved.  I have had to contend with a few myself, particularly when working with Sega System 32 and a few other stubborn things.

As far as your other issue, you won't have to rely on one source for everything.  There are always alternatives.  Myself and others will gladly help you have the best experience on Mini NES/SNES/PSC!  It is all about the enjoyment factor.  Mini NES/SNES is quite stable.  PSC still needs a little more time and patience to be a more beautiful thing.  But, we will get there!

I am supportive of hakchi, bleemsync, autobleem, retroboot, and the unreleased pspwned.  You definitely have your options and need not be tethered to just one!

**Comment by missionfloyd** [comment]
Perhaps I wasn't clear. You are _required_ to disclose the source code one way or another.

Besides, it would help clarify what you're actually doing to these cores.

The bleemsync devs refuse to disclose source too. Don't stoop to their level.

**Comment by Mte90** [comment]
As I can see on reddit all the various core has different features (like chd support as example) compared to the original, so I guess that are changed. 
So why not release this changes to the original project?

I am trying to understand why this kind of modifications are not part of retroboot and what are the real differents.

Also releasing an exe to inject the new files is not so useful when people like me is using linux, so maybe that injector is doing also other things to retroarch that we don't know.

**Comment by KMFDManic** [comment]
@Mte90 Generally, for "any" changes to be committed to "Official" Libretro, it would need to pass fairly strict scrutiny as far as stability and whatnot.  I tend to work mainly with "lower spec" hardware model platforms, such as the NES/SNES/PS Classics.  We cannot run many things very well.  So, a few tweaks that would have absolutely zero impact on most other Platforms, are very beneficial for us.  Some commits that "do" benefit other platforms, have been pushed into "Official" standards for Libretro.  Such as some of the MAME 2003 Xtreme commits, like fixed up Irem/Nintendo Vs Sound, Custom OSTs for games like OutRun, NBA Jam, Final Fight, and so on.  

As far as RetroBoot, THESE ARE part of RetroBoot, as Genderbent, who works on RetroBoot...I share whatever latest stuff I have worked on with him, and he posts it with RetroBoot.  It would take ions to go every little change or addition.  Most of them would be nonsensical to the every day user.  But, something like .chd support, obviously...would be quite impactful.  We implemented .chd support for PCSX ReArmed NEON a few Releases back.  It already works with latest RetroBoot Release, as well as my own personal Release.  And, other platforms can benefit from it, as well:)  

I do things to account for what people give me feedback on.  For instance, some complained that Metal Gear Solid had glitchy FMV cinema screens...SO, we got the Video Plug-In for PEOPS implemented:)  So, running PCSX ReArmed PEOPS from my latest Release will have fixed FMVs for Metal Gear:)  Let me know if you have any other questions.

**Comment by Mte90** [comment]
Thanks for the clarification, I read the various posts on reddit but wasn't clear the difference with the official latest retroarch and your version.
Also because I read the previous posts but was very confusing.

Anyway release the patch/diff files can improve the awareness of the project and maybe involve more people on improving them. I can understand the policy of libretro but without release the code changes there will be always diffidence or apply them mannually in case of other needs. Also if they are already included in retroboot or not.

Maybe it's me that like a lot to read changelog and see the difference and do comparison (and your changelog include a lot of stuff but not very technical more about tests).

About the linux issue of the injector I did manually. Taking the *.so core files  that I wanted and replaced inside retroarch.

I very highly appreciated the enhanced versions of the emulators especially for PSP/N64 that are the most problematic on PSC as example.
