### ISSUE TITLE
Reicast Xtreme Record of Lodos War Freezing at certain areas.

### ISSUE THREAD

**Issue by rmatheso** [KMFDManic/NESC-SNESC-Modifications#169]
Latest Retroboot 0.71 on PSC with Reicast X-Treme Core.

Record of Lodoss War freezes on first battle, also with the goblin boss. This problem was apparently fixed in other versions of Reicast. (or turning off the dynarec). Updating reicast with "dynarec safemode"

Issue could be fixed with this:
https://github.com/libretro/reicast-emulator/pull/206

https://github.com/reicast/reicast-emulator/issues/84

**Comment by KMFDManic** [comment]
Did you, by chance, try it with Reicast Accuracy?  The problem with even disabling dynarec, is that it will slow games down to an absolute crawl...I use the same "concept" with games like Jedi Power Battles.  Problem is, every time you disable dynarec, then bypass the crash point...It will reset the moment you reenable it, if dynarec is the causal crash reason.  The "div" may potentially be possible.  I would definitely suggest trying it on Accuracy, first, and let me know.

**Comment by rmatheso** [comment]
Yes, tried it with the Accuracy core and same thing. Freeze at the first fight with the goblins. Speed is great on both cores though!

**Comment by KMFDManic** [comment]
@rmatheso Sort of a catch 22 in this case.  Without dynarec, the game will be abysmally slow and pretty much unplayable.  How far from "beginning" of the game does the first crash happen?  I might have an idea as to how to potentially work around it.  I will check into it with a personal test or two.

**Comment by rmatheso** [comment]
It's pretty close to the beginning. After the tutorial on how to open chests, you move to a room where you have to walk over 4 switches, a goblin appears and you fight a bunch of goblins. It crashes here. I'd say maybe 4 minutes into the game. I can post a video if need be.

**Comment by rmatheso** [comment]
Here is the video 
[link]https://www.youtube.com/watch?v=pkue248-W-M&feature=youtu.be(url)

**Comment by KMFDManic** [comment]
@rmatheso Unfortunately, it is pretty much as I suspected it to be.  The DIV workaround is needed for a select other number of games, too...such as:

Demolition Racer, Record of Lodoss War, Star Wars Episode I: Racer, Pro Pinball Trilogy, Surf Rocket Racers.  With the lower spec hardware of the Mini NES/SNES/PSC, this is not the most viable workaround, if affecting speed and performance.  Even the disabling of dynarec that you first referred to would make it really unplayable.  Question is, if you have DIV Matching on, bypass a crash point, the game probably crashes around 2-3 minutes later?  If so, that is same behavior as games that have similar issues on PS1 Cores, like Star Wars: Jedi Power Battles.  Very cool game, though.  I haven't personally played it!  I will still do a little test and see if I can find another alternative workaround, without needing to slow the game down.

**Comment by KMFDManic** [comment]
@rmatheso Unfortunately, due to the limitations of the NESC/SNESC/PSC, the only way around that currently is without Dynamic Recompiler, which would run the game at a snail's pace.  We simply do not have powerful enough hardware to handle it without Dynarec.  For now, I am going to close the issue, as hardware limitations won't make it optimal, even if fixed up.  The disabling of DIV matching would be much akin to running without Dynarec.  So, this is a lose lose situation, either way, at least in the current state of things, hardware/software wise.  But, I will keep this game on my "test" setup, and see if some "other" workaround can be gained.  Again, great game showcase, and thanks for the heads up on the DIV conflict.  Looking forward to other showcases you do!
