### ISSUE TITLE
BlueMSX core

### ISSUE THREAD

**Issue by ArieKindicator** [KMFDManic/NESC-SNESC-Modifications#17]
You are doing a great job by adding and updating all those additional cores and the necessary dependencies!
I did some test with MSX games. The default MSX machine/systems seems to be MSX2+ (and which is okay, btw).
However, manually changing the emulated system/machine from default/auto to MSX1 or MSX2 results in:
1. the emulated machine does not change; it boots up as a default MSX2+ machine, or
2. retroarch hangs when you change the system/machine (for a second time). Reboot of the SNES device is necessary. C8 error.

Tested with: SNES EU/Hakchi2 2.0.21.72; fmsx completely uninstalled, including all bios files (which I checked using FileZilla).

Notes
- uninstalling bluemsx core / bios doesn't remove the bluemsx.ini and bluemsx_history.ini files (in the systems folder).
- loading the blueMSX core without a game; the MSX machine doesn't boot to the command prompt of MSX BASIC (as fmsx does correctly).

**Comment by KMFDManic** [comment]
Welcome to one of the nuances to get accustomed to, within the Mini NES/SNES Environments.  In general, when loading a Core by itself, many will not have ability to pull up Core Options, unless a game is loaded.  Also, being that RetroArch is geared more towards PC, as its mainstay, other attributes come into play, as well.  Save State and Config locations, for instance.  In the case of BlueMSX, it is superior in accuracy to fmsx, although fmsx is more user friendly, and is still an excellent Core!  In the case of BlueMSX on our set-ups, if Auto works, I would strongly suggest just leaving auto enabled:)  It has worked fine for me in my testing.  Adjustments had to be made for RetroArch to even work on the NES/SNES.  But, for what its worth, we are getting a hell of a lot of bang for what we can currently run!  When scenarios rise, such as your BlueMSX one, a workaround is sometimes necessary, or just acceptance.  Cache/Ram overload tends to cause C8 Errors in cases such too much Folder Surfing, Playing N64 Games for long periods of time, and even changing various RetroArch Settings!  I typically reboot the system on a fairly frequent basis so as to avoid some of the C8 Errors.  Also, many options in RetroArch are tied to a computer keyboard, and when enacted, instantly freeze the NES/SNES, such as some of the audio settings.  The .ini files that were not removed, have you checked to see if any BlueMSX additions were auto-added within RetroArch Core Config file?  In the case of Dosbox, to fix the Emulator from crashing, after changing a "bad" setting, the entries would simply need deleted from RetroArch Core Options:)  In my testing of BlueMSX, every game that didn't work in Fmsx, worked quite nicely in BlueMSX!  So, I will definitely be sticking to BlueMSX, since it has the double whammy of being able to play ColecoVision:)  Check your RetroArch Core Options file, and let me know.  Just remember, these Cores and RetroArch are generally foreign to the Mini NES/SNES Environments, and we have to make some minor sacrifices and adjustments along the way to get them to play nice with one another!  Thanks for your input!

**Comment by ArieKindicator** [comment]
I agree, i also prefer blueMSX over fmsx. You are doing a great job.
At the moment i'm testing some converted .dsk to rom files (as I don't know how to run .dsk directly from the command prompt; if even possible).
Convertion of single dsk games seem to run just fine when in MSX2 mode, other machines end up in either a boot loop or go straight to the MSX Disk/basic command prompt.

- dsk2rom.exe: http://home.kabelfoon.nl/~vincentd/

(use SCC mapper [default]; ascii8 mapper might result in graphical distortions; no compression *)

* optional: manually compress the converted output rom with 7zip on a PC as any other rom file

Oh Shit! has some 'speech' and is played correctly with bluemsx but not with fmsx.

**Comment by gingerbeardman** [comment]
You might also want you try "verified" sets of disks with lots of games. As close to nointro style you'll get for MSX. Google "MSX Mania Collection"

**Comment by KMFDManic** [comment]
@ArieKindicator Good job on the testing of various perimeters.  This is generally how I proceed when working with new Cores.  There are obvious nuances to adjust to, since we do not always have 100 percent reliability/compatibility.  But, digitized speech for Oh Shit! is the icing on the cake:)  Everything is set in place, Bios wise.  So, it is mainly a matter of best getting used to what we have to work with.  I will, of course, be updating BlueMSX in my next update with a few minor changes:)

**Comment by KMFDManic** [comment]
I will leave close this issue, as it is related to our somewhat uncontrollable environment, more so than the Core, itself. But, due to the complex nature of this Core, feel free to reply anytime.  It will be an place for us to discuss any findings with this truly excellent Core.  Anything we find or discover, I will do my best to get merged into the Core with Updates:)
