### ISSUE TITLE
Notifications at top left of screen can't be turned off?

### ISSUE THREAD

**Issue by bolton80** [KMFDManic/NESC-SNESC-Modifications#172]
### Step 1: Describe your setup:

  * hakchi2 CE version: 3.5.3
  * retroarch used (filename): 176 extreme  * hmod(s) used by the game you are having problems with (filenames): any
  
### Step 2: Describe the problem:
  
  * Hopefully this is a quick fix, but how do I turn off the notifications at the top left of the screen when starting every game. These notifications are for thing like clovercon or loading overrides etc. I tried turning notifications off in the menu, but doesn't make a difference.

It just irriates me (I'm weird!). Any advice please?
  
### Notes: Are you in the right place?

  * For issues or feature requests related to hakchi2CE goto [TeamShinkansen/hakchi2/issues](https://github.com/TeamShinkansen/hakchi2/issues) and file a Github issue.
  * For general usage questions, post a question on [Reddit](https://www.reddit.com/user/MDFMKanic/) or the [Nintendo/Sega/Sony Classics Discord](https://discord.gg/bX9PqrC)

**Comment by gingerbeardman** [comment]
Is this the retroarch option? 

`Settings > Onscreen Display > Onscreen Notifications > Onscreen Notifications = OFF`

**Comment by bolton80** [comment]
Yes, that’s the one. Doesn’t seem to actually turn them off though. Unless of course I’m not saving the setting properly. How can I tell?

**Comment by gingerbeardman** [comment]
> Yes, that’s the one. Doesn’t seem to actually turn them off though. Unless of course I’m not saving the setting properly. How can I tell?

You will have to restart RetroArch to see that particular change.

**Comment by KMFDManic** [comment]
@bolton80 I enabled the Notifications, as they are pretty important for many of the newer additions for RetroArch Xtreme, as well as very helpful in troubleshooting, when others run into problems.  If you do want it disabled, however...Best way to do it is have RetroArch UI from the KMFD Mod Hub, open up RetroArch from Main UI using that new "Game", once you export or synch, then what gingerbeardman mentioned above.  Then, exit, and Onscreen Notifications should be off.  If they don't stay off, you can go to RetroArch Settings, Configuration, Save Current Configuration.  Again, I would suggest leaving them on, as they are quite helpful, especially if you want to do playlists and to confirm things are operating properly.  Keep me posted:)

**Comment by AntiFly** [comment]
yeh please turn this off, this is even happening in v1.7.7 and really sux. ;)

**Comment by gingerbeardman** [comment]
I think this is the new retroarch default, no?

**Comment by KMFDManic** [comment]
@bolton80 @gingerbeardman @AntiFly 

Works best if you use RetroArch UI from Main UI, which can be grabbed from KMFD Mod Hub, Games Tab.  

Once in RetroArch Settings:

- Settings, User Interface, Menu Widgets Off

- Settings, Onscreen Display, Onscreen Notifications Off

If you attempt to do some changes from certain Cores, they won't save.  This way saves every time.

Notifications are on by default because it is an incredible asset with troubleshooting and for Scanning Playlists, controller configurations, etc.  This just happens to be one of those things where more people preferred them on than off..Much like the "loading" screens that I removed awhile back.  But, I always help everyone have things the way they want, in the end:)
