### ISSUE TITLE
SNES Crash on current Update

### ISSUE THREAD

**Issue by AntiFly** [KMFDManic/NESC-SNESC-Modifications#192]
### Step 1: Describe your setup:

  * hakchi2 CE version: 3.5.3
  * RetroArch used (filename): _km_retroarch_179_xtreme(oc/auto)
* Using OTG

Ive patched to current Update. I have installed the device twice from scratch.
Several modules are not working as expected.

* snes games are not loading anymore.
* naomi / dreamcast games dont load or show hint that i should use mame otherwise expect issues and it will crash then with c8 error.
* some n64 ames not loading
problems in almost every core.

system crashes on dreamcast games after about 1-5 minute play.
I am using a original Samsung 5,3V / 2A Adapter which works great so far...
so unfortunally it seems not to work with my device at all ;(

**Comment by AntiFly** [comment]
same problems without overclock installed on retroarch 1.79 oc manual
was there a major change i didnt get notice about ?
even mario and yoshi is not working (snes)  falls back to menue.... wtf ?

**Comment by AntiFly** [comment]
if i reflash with retroarch 1.77 everything works fine. so i will test next release otherwise i stick with the old.

**Comment by KMFDManic** [comment]
It would seem that Overclock does not work for your system.  If you hook up system to hakchi, go to Tools, Telnet, type in root  Then, hakchi overclock boot, which will set system back to normal spec.  SNES9x 2016/18 should run identically on speed now.  The one 2018 one I posted before is no longer in my set.  But, let me know how things are running for you on 18.

SNES games are working fine for me on all of the 9x Cores, as well as Canoe.  The commands are still:

/bin/snes02, /bin/snes05, /bin/snes10, /bin/snes16 (for Bright, now), /bin/snes18

Dreamcast can crash if you are attempting to run with Xtreme OC, and your chip doesn't support it, due to not being as high quality a chip, quality assurance wise.  With OC deactivated or uninstalled, and DC Bios in place, Dreamcast games, lst files, etc, run fine with Reicast Xtreme.  Flycast Xtreme does not need .lst, so use .bin/.dat instead  Just rename the extension in hakchi, and it will update to the desktop files.  Test out the Volgarr the Viking Game from Mod Hub, as a good DC test game:)

So, try to make sure your system is running at default, since OC doesn't seem to be viable for you.  Then, install/repair kernel, if need be, then things should be fine.  Keep me posted:)

**Comment by AntiFly** [comment]
Snes18 is not set tot he commandline preview ?



 

So i took the one from the emulator view



 

Von: Kyland K <notifications@github.com> 
Gesendet: Dienstag, 22. Oktober 2019 01:21
An: KMFDManic/NESC-SNESC-Modifications <NESC-SNESC-Modifications@noreply.github.com>
Cc: AntiFly <mazterz@gmx.at>; Author <author@noreply.github.com>
Betreff: Re: [KMFDManic/NESC-SNESC-Modifications] SNES Crash on current Update (#192)

 

It would seem that Overclock does not work for your system. If you hook up system to hakchi, go to Tools, Telnet, type in root Then, hakchi overclock boot, which will set system back to normal spec. SNES9x 2016/18 should run identically on speed now. The one 2018 one I posted before is no longer in my set. But, let me know how things are running for you on 18.

SNES games are working fine for me on all of the 9x Cores, as well as Canoe. The commands are still:

/bin/snes02, /bin/snes05, /bin/snes10, /bin/snes16 (for Bright, now), /bin/snes18

Dreamcast can crash if you are attempting to run with Xtreme OC, and your chip doesn't support it, due to not being as high quality a chip, quality assurance wise. With OC deactivated or uninstalled, and DC Bios in place, Dreamcast games, lst files, etc, run fine with Reicast Xtreme. Flycast Xtreme does not need .lst, so use .bin/.dat instead Just rename the extension in hakchi, and it will update to the desktop files. Test out the Volgarr the Viking Game from Mod Hub, as a good DC test game:)

So, try to make sure your system is running at default, since OC doesn't seem to be viable for you. Then, install/repair kernel, if need be, then things should be fine. Keep me posted:)

**Comment by AntiFly** [comment]
Hey man,

 

ive tested it, ist definitly not working with cmd /snes18, but snes is working with the new command shown in emulator specs.

 

Ive got massive problems even with telnetet „hakchi overclock boot“ system shows 45 degrees.

Mame2003 (raystorm) is just crashing and some other, dreamcast flycast is not working on loading .lst files. Ok got it and set to .bin this loads up but super slow speed and crashing.

It feels just bad for me ;(

 

Could you supply me your last release with retroarch 1.77 ?

I missing the snes16 release as well i want to load the hmod and use it cause 2018 is super slow for me.

 

Even if i use the manual mode and dont select anything for overlock (resetet kernel) it does not work properly so ist something related with retroarch as well (as for my suggestion)

 

cheers

 

Von: Kyland K <notifications@github.com> 
Gesendet: Dienstag, 22. Oktober 2019 01:21
An: KMFDManic/NESC-SNESC-Modifications <NESC-SNESC-Modifications@noreply.github.com>
Cc: AntiFly <mazterz@gmx.at>; Author <author@noreply.github.com>
Betreff: Re: [KMFDManic/NESC-SNESC-Modifications] SNES Crash on current Update (#192)

 

It would seem that Overclock does not work for your system. If you hook up system to hakchi, go to Tools, Telnet, type in root Then, hakchi overclock boot, which will set system back to normal spec. SNES9x 2016/18 should run identically on speed now. The one 2018 one I posted before is no longer in my set. But, let me know how things are running for you on 18.

SNES games are working fine for me on all of the 9x Cores, as well as Canoe. The commands are still:

/bin/snes02, /bin/snes05, /bin/snes10, /bin/snes16 (for Bright, now), /bin/snes18

Dreamcast can crash if you are attempting to run with Xtreme OC, and your chip doesn't support it, due to not being as high quality a chip, quality assurance wise. With OC deactivated or uninstalled, and DC Bios in place, Dreamcast games, lst files, etc, run fine with Reicast Xtreme. Flycast Xtreme does not need .lst, so use .bin/.dat instead Just rename the extension in hakchi, and it will update to the desktop files. Test out the Volgarr the Viking Game from Mod Hub, as a good DC test game:)

So, try to make sure your system is running at default, since OC doesn't seem to be viable for you. Then, install/repair kernel, if need be, then things should be fine. Keep me posted:)

**Comment by KMFDManic** [comment]
To confirm, .lst files will ONLY work with Reicast Xtreme.  I maintained that coding because I wanted a bit of Legacy Support for them.  Flycast does NOT use them at all.  They are merely .cue files pointing to the data files.  But, now, Flycast can smart detect what needs detected, simply by loading .bin/,dat files.  

For Overclock, remember to telnet, type in root, Enter, then 

- hakchi overclock (to test current temp/Mhz)
- hakchi overclock boot (to go to default Mhz)
- hakchi overclock max (to go to Max OC)

1.79 Without OC installed/Active will operate no differently than 1.77

As far as SNES, I can repost 2016 if you truly feel you want me to.  No problem there:)  Temps you are getting, if at 45, aren't bad.  But, the key thing here is that not ALL systems will work with OC.  They only tested to ensure chips can make it to 1.2 Ghz.  Many Many chips can go past that, even up to 1.5 Ghz.  But, those that cannot will simply crash or reboot the system, doing no permanent damage.  If you are getting crashes, it is due to "bad" chip, and/or improper hardware configuration to support it.  

I will make sure you are back in action.  But, don't use .lst files for Flycast.  They won't work.  Only use them for Reicast:)  You can simply change command lines to reflect the .dat or .bin files instead, and they will load fine.  If they still crash, then OC is why they are crashing.  Setting hakchi overclock boot will fix that problem instantly:)  

Looking forward to your response, and as always, I will make sure everything you need goes into the Next Release:)

**Comment by KMFDManic** [comment]
Also, please confirm exactly what games are running slower for you on SNES9x 2018, as everything should be running fine on current 2018.  I have no problem reposting, though, if you can confirm there are issues with the games you refer to!

**Comment by AntiFly** [comment]
Heya,

Ok i reflashed to 1.77 yesterday again and tested raystorm mame2003 there as well it get stuck at green loading screen. Maybe it works longer not choosed test games randomly.
I will test 1.79 once more maybe this evening.
What really sucks is that green info bar while loading dreamcast games .. blabla please juse mame. Could you disable this?

I have a bad feeling about my snes ... hoWever I report my results as always.

Cheers

Von meinem iPhone gesendet

**Comment by AntiFly** [comment]
oh... not cool that e-mails got added with header ^^

**Comment by AntiFly** [comment]
I did now following.
- device reset
- reinstall kernel
- install hmods
- update command lines
- update usb stick for otg
-> i discovered that a complete menue entry (SNES) is missing, and GENESIS is displayed at RETURN.
that is super strange, whats going on with my device ?

**Comment by KMFDManic** [comment]
@AntiFly Yes, responding from emails will show your email.  I had intended to edit those out when I got home from work.  But, you got to it before I could.  As far as your USB acting strange.  If you got crashes and such, there may be corruption.  Do a disk check on the drive, then reexport.  This would have nothing to do with the system, itself.  This would be relative to USB and or improper install/repair kernel.  I really appreciate your test feedback.  I wish Overclock was supported for you, really!  But, your other option is to get a Playstation Classic, which has better performance and speed than even SNES Overclock!  Let me know on anything else, especially SNES9x 2018 and if you want me to repost 2016!  I am changing things so ALL Command Lines that each Core can run will display in the ReadMes!  Any you are fond of, I will ensure are in the Release, if you can respond in time:)  

Flycast Xtreme will run awesome for you, once you are back in action!  Just do a disk check and let me know how things go:)  And, also, sometimes...that behavior is indication of an OTG device going bad.  So, don't rule that out, as of yet.  I will keep in contact with you til you are happy with everything again, no worries!  

Kyland:)

**Comment by AntiFly** [comment]
indeed, found out that the .desktop files are missing within .hakchi\games\000\
i  formated the hole drive and do re-export now. this will run about 4hours from now.

ill keep you posted ;D

**Comment by AntiFly** [comment]
re-flahsed as i told, refilled usb stick.
retroarch 1.79 oc manual ( no specific oc settings )
flycast: 
- dolphin blue not working

mame 2003:
- RayStorm not working

**Comment by KMFDManic** [comment]
If "saves" do not matter for you, Factory Reset the Mini, itself, and it will wipe all saves.  Then, attempt to load F-Zero X, Mario 64, or Star Fox 64 with Glupen.

Flycast working absolutely fine for me.  But, it will NOT work with .lst files, period, as they are not necessary for the Core.  Also, you may still be trying to use the .bin/.dat files we were testing with before.  They are not the optimal ones to use.  Instead of naomi_boot.bin, which is needed to run .bin/dat. files, naomi.zip is all you need to run MAME roms with Flycast!  Yep, we can simply run the MAME versions, in zip format:)  Ikaruga will work with the .zip+.chd combo!

Just do not forget, you CAN'T use .lst files, whatsoever, with Flycast.  They will crash, since they are no longer applicable to the Core.  But, they do work fine with Reicast.  I can retest some games, on my end, and compare notes.  If need be, I can make a few adjustments to account for any deviations.  But, I am running all of the Dreamcast Games fine with Flycast Xtreme, and the Naomi/Atomiswave .bin/.dat+.lst Games I run with Reicast Xtreme.  And, MAME games with Flycast Xtreme:)

So, make sure for your Flycast Retest, your system is at 1.2 Ghz and you are trying MAME roms.  I will follow-up with you, no worries:)

I will check on Metal Slug 6 Violent, as well.

Anything else you need me to retest, just respond here.  :)

**Comment by AntiFly** [comment]
here we got the point.
I missed the information that the "old" bin.dat files wont work at all, I thought it just not work with .lst loading so i switched this for the cmd to .bin!
I have both in bios naomi.zip and naomi_boot.bin as well.
so for my point it will definitly not work with current flycast hmod and loading a .bin i tested in the past. which is working with flycast from Cores_9-9-19. (check on that).

I will test the games again with .reicast-xtreme. since i used just the .reicast command. now i saw in bios the xtreme switch (i cant remember there was a xtreme switch here and for what this is to be used) ?

I now will check the shit again with 3.6.0.
Have to refill usb stick again cause since upgrade it was not possible to compare data. ;-)
I will check on the mame roms, have to look in my set for them first ;)

**Comment by KMFDManic** [comment]
I just did a retest, and the OLD .bin/.dat files working fine for me on Flycast, tested Dolphin Blue, fine.  Overclock OFF.  Then, tested MAME version of Dolphin Blue, also ran fine.  Then tested ikaruga .bin/,dat version, fine.  And, finally ikaruga MAME rom with chd, included.  have ikaruga.zip and ikaruga folder in same directory, with the chd inside ikaruga folder.  Load the ikaruga.zip with Flycast Xtreme.  MAME roms all working great.  You WILL need awbios.zip in order to run MAME versions of Atomiswave games.  It is roughly 38 KB in size.  Don't use the 17 KB one:)  

The xtreme for Reicast and Flycast are just alternate Command Lines that can be used.  Only a few Cores actually switch to variants, such as PCSX ReArmed NEON, PEOPS, UNAI.

Let me know how N64 runs once you clear saves, if you don't have any that matter.

IF DC Crashes, you may have OC on.  Just connect and telnet it to 1.2Ghz, then test again.  My one system runs DC fine with OC.  The other one does not.  Again, it is all about how good the chip is that you have:)

**Comment by AntiFly** [comment]
awbios.zip
crc32 
* 719B2B0B
* D3E80A9F

??

**Comment by AntiFly** [comment]
Update:
Discovered something intresting.
obviosly I ran my setup with an outdated awbios.zip and naomi.zip which made it possible for me to play the named atomiswave games in a acceptable speed with Flycast.
I now switched bots zips to MAME.0.212. I am now able to run OC Dreamcast at least for some minutes, after i put mini back to pc it still has 48 degrees but crashed. anyway the more intresting thing is that now dolphin blue is running but gets after some secs so super slow that it is still unplayable for me.

**Comment by KMFDManic** [comment]
Naomi/Atomiswave games are more cpu intensive on the NEWER Flycast Xtreme, versus the less intensive OLDER Flycast Core.  The exact same scenario is why I separated the coding for FBA into FBA 2016 and 2018!  On the Playstation Classic, power draw effects the system if running a flash drive in USB Port number 2, without a Powered USB Hub to sustain it.  Sony implemented a safety measure to attempt to prevent modding, in the way that, too much power will crash the system.  So, for example, having a 16 GB flash drive in port 2, then attempting to run FB NEO or FBA 2018, will crash the Core and/or RetroArch, due to using too much power.  But, FBA 2016 WON'T:)  

Older Flycast coding is absolutely useless for running Dreamcast Games.  But, it is quite viable for Atomiswave/Naomi Games.  So, I will work that coding to be exclusively meant for Naomi/Atomiswave games as its own Core.  

This ALSO Means OC will crash more on your lesser chip system with Flycast Xtreme, but not so much as often with Flycast "Legacy"!.

A few Cores that require some Legacy Support will be Just that...

FceuMM Legacy is because they changed the save format, and some who retain older saves need to use Legacy, til they move onto the newer save format.

PPSSPP Standard, which will change to Legacy Next Release, is because the OpenGL Driver implementation changed in Xtreme, and is more accurate.  But, without GLCore implementation, Frame Skipping and Auto Frame Skipping Can NOT be used for ALL games.  But, with PPSSPP Legacy, they can.  So, the very very very very select few number of games that require Frame Skipping to run better on MD-S-NESC are better with Legacy.  But, Ultimate Ghosts N'Goblins is not accurately displayed with the older OpenGL on Legacy...But, it is on Xtreme:)  Fun stuff!

I am making changes to P-UAE Xtreme, as well, as there are a few nuances to adjust to, as far as that is concerned, too!

Last, but not least...We have MAME 2003 Plus and Xtreme.  Xtreme follows a Legacy Core Set, but also codes in 300+ newer games and dozens upon dozens of new additions, including speed hacks, to make it run more so like a 2019 Core!  Plus has a slight performance and speed loss, but is still a wonderful companion piece to Xtreme.  Those who work on Plus also help collaborate on Xtreme, and vice versa.  The Macross 2 Arcade Game was broken in ALL MAME 2003 coding, til we implemented it, fix wise, into Plus/Xtreme.  

The games you detailed in your other issue, due to how the coding has changed, I may separate into MAME 2003 Legacy Coding...as in /bin/mame2003-legacy

That work for you, mate:)?

Yes, despite the lesser chip, you can still run OC to a degree..Just not with more cpu intensive Flycast Xtreme!  You're actually lucky to be able to get any DC going with OC, on the lesser chip.  My one system's chip can also only handle OC with it, for a little at a time.  My other one runs it flawlessly each and every time.

Dolphin Blue, play the first stage, til you get to the "tunnel"...It runs super fast there, and in many other parts til the end of the game!  I will show it in a video!

Thanks again:)

**Comment by AntiFly** [comment]
hey man,
thats great to hear.
I will test that shit as everytime ;-)
it would be also very handy if there will be a list of common known issue games and best core for them.

**Comment by KMFDManic** [comment]
@AntiFly Feel free to open another issue and/or email me if any other issues.  But, you should be running Dolphin Blue better upon Next Release:)
