### ISSUE TITLE
Mame 2003 Xtreme games wont load anymore

### ISSUE THREAD

**Issue by AntiFly** [KMFDManic/NESC-SNESC-Modifications#195]
### Step 1: Describe your setup:

  * hakchi2 CE version: 3.6.0
  * RetroArch used (filename): 1.7.9
  * hmod(s) used by the game you are having problems with (filenames): 2019-10-25
  
I am 100% all of these games worked on older Retroarch Core / HMODs.

So for MAME 2003 XTREME:
I have retested all of my added Mame 2003 xtreme Roms.

not working games for me at the moment:
- Ray Storm (bootstuck - green screen)
- Street Fighter EX Plus (bootstuck - green screen)
- Street Fighter EX2 Plus (bootstuck- white,yellow stripe)
- Denjin Makai 2 (Guaradians) (blackscreen - crash to menue)
- VAMF x1/2 (blackscreen)

could you doublecheck on that or maybe i need to update some files cause u did compatibility updates recently ?
cheers

**Comment by KMFDManic** [comment]
@AntiFly Again, thank you for the sheer amount of testing and personal feedback over the last 2 Releases!  You also get to see just how much testing is required for myself, when I do these Releases!  In lieu of some of your feedback, as well as others, I am always constantly adapting the Releases.  We get new toys to play with, as well as get old ones fixed if they succumb to the Butterfly Mod Effect.  So, as far as your testing goes, I will make a few changes, and let you test:)

May I ask "how" many games you tested with MAME 2003 Xtreme?

**Comment by AntiFly** [comment]
@KMFDManic 
ive got 51titles added and tested.
the rest i run with FBA2016 :)

**Comment by KMFDManic** [comment]
@AntiFly Legacy MAME 2003 Support Next Update:)

**Comment by AntiFly** [comment]
@KMFDManic ive read about no Mame 2003 Support ? is it avail or not now ?
;)

**Comment by KMFDManic** [comment]
@AntiFly I actually tested these games on current coding of MAME 2003 Plus/Xtreme/Standard, and they all had issues.  Do you remember the last time you, for sure, was able to run any on MAME 2003?

**Comment by AntiFly** [comment]
@KMFDManic 
I am not able to start these games on mame 2003 xtreme anyway it just crashes.
I tested them in the early days of your plugins, i dont remember exact month or something, but it was quite in the beginning of this scene ;)

**Comment by KMFDManic** [comment]
@AntiFly In my testing, none of the games in question, from this issue work on any MAME 2003, currently.  Luckily, versions of them work on Final Burn Alpha Cores, PS1, etc.  If I can find coding that works with any or all of them, I will get that reincorporated as MAME 2003 Legacy Support.  But, til I am able to pinpoint, I will stick with Xtreme/Plus in the meantime.  I think the ONLY Core that may need Legacy Support added will be Flycast, which is entirely due to "power draw memory limitations", which I will help you overcome!

**Comment by Playstationclassiclover** [comment]
Hi, I know this is a very long time after that I am adding a comment to this request :) I'm doc browning this haha

But basically I encountered the green screen issue on some Namco games on Project Eris, using the KMFD Mame cores on the Playstation classic.

SO, I decided to do a really thorough check of around a 100 games and captured the data. I actually found around 36 3D games that are pretty playable. Including Prop cycle, which runs at full speed but has no sound in the KMFD Mame 2003 Extreme core,

Then there are a lot of Capcom Zn1 and Zn2 games that are running almost full speed with sound (Using 8 frameskip)  in the KMFD Mame 2010 core, including Strider 2.

Seeing this stuff run is such a buzz! I have attached a document with all the data, hopefully some of it might help to make improvements for these games.

Also, I totally understand the butterfly effect; it's something that has plagued Mame for years. And I don't know how feasible it is, but maybe for the mini consoles, the cores could be forked and tweaked specifically for Namco and Sega 3d stuff.

Like the old Zinc emulator for Namco 3d Used to run super fast on my old laptop 14 years ago, as did the model 2 standalone emulator. Maybe with some of the Mame drivers cutout, these could be optimised for Namco and Sega?

I know a talented developer over on the dreamcast talk forum created something he called "SGA" (Single Game Arcade) where he trimmed mame down and made it compatible with just one game at a time to get it running on the Dreamcast.

Anyway just some thoughts and data :)

[3d arcade games tabled results.docx](https://github.com/KMFDManic/NESC-SNESC-Modifications/files/9260981/3d.arcade.games.tabled.results.docx)

**Comment by KMFDManic** [comment]
@Playstationclassiclover Thanks for checking out my stuff:)  One thing to note, Project Eris isn't optimal for usage with the Xtreme Cores.  You may want to switch over to AutoBleem, especially when I post the Next Update.  Just moving stuff over to Eris will not work properly, since Eris uses different power draw settings than the finely tuned AutoBleem Xtreme I post.  SO, more intense stuff is likelier to crash or not work at all, elsewhere...such as CAVE Shmups, Killer Instinct Arcade, etc!  

https://www.youtube.com/watch?v=j3hM_vVlTyg

As far as your test list, test results are always fascinating.  I may be able to broaden your horizons quite a bit, however...as there are many things you are completing missing out on:)

- Sony Zn-1/Zn-2 Games are definitely most optimal running their PS1 Counterparts
- Air Rescue works fine with 2003 Plus.  I can add it to 2003 Xtreme, though!
- SegaSonic the Hedgehog works...may need to use alt rom set.  But, it eventually will crash in the "ice stage".  This cannot be fixed.  Game works "fully" on Core/s I will be posting next Update, though!
- Sega STV mostly work fine on Yabause Xtreme with the AutoBleem/Xtreme Injector setup
- Games like Waverunner, which fit into the Naomi Arcade Category, run fine with Flycast Xtreme, as do any other "Dreamcast Ports" of games like Zero Gunner, etc, too!
- Star Wars Arcade works with MAME 2022 Xtreme!

There are many more examples.  I tend to go case by case scenario, since I mentally note any game I have tested, for the most part.  I don't really keep lists.  I just most remember what works, and fix things if I can!  Some games you encountered missing sound, etc on, are quite complicated to fix, and really not worth the time and effort, since several of those do luckily have alternate versions we can play, as well.  Prop Cycle is still a fun one to play, however.  Might be worth retrying that with MAME 2022 Xtreme.  

MAME 2010 is no longer the best Core to use for nearly EVERY game you have test results on.  They have potential to function WAY better on 2015 Xtreme/2022 Xtreme, and an incoming 2014 Low Profile Xtreme Core I have for next update.  Reason why...you can't reverse overclock with 2010!  But, you can with 2015, 2022, 2014 Low Profile!!!  This means, you can pretty much run about any game you wanna run!  

Note, the frameskip I had adjusted into 2010, is actually not as optimal as the updated Stuff I got in, for 2015, 2022, 2014 Low Profile.  I have CAVE Shmups running fairly well, with 0 Frameskip, with the Next Update, per this video:

https://www.youtube.com/watch?v=2Zwnqz_EObI&t=607s

You are always welcome to join our Discord, too, and we can directly communicate, test, etc:)  Another update will pretty much be ready to go around Aug 28th!

https://discord.gg/XT9wzuxT

**Comment by Playstationclassiclover** [comment]
@KMFDManic Hey thank you for the reply, and in fact I haven't said it yet, but thank you for all the hard work, it's much appreciated!! You are a legend dude! :) I know the PSC wouldn't be anywhere near as useful without your updated cores!

I will admit that I am tempted to try swapping to Autobleem, but it boils down to ease benefit... I have put so many hours into setting this up so far. Way more than I should given the other things in life that I should be concentrating on. But this triggered some type of OCD in me and I just had to get it up adn running haha.

But I think it's a testiment to your coding, as it's running nice in project Eris; Flycast xtreme is running Naomi and Dreamcast full speed, Ludicrous is running N64 full speed; and I had all my 2d stuff running in FBNEO xtreme, but a few like Mortal Kombat, Metal Gear 2 etc were running slow, so just swapped to Mame 2003 Xtreme for them and full speed now :) and gonna blend in those 3d that are working and rescrape those folders.

That's a good point about the Zn-1 and Zn-2, I always think of playstation emulation as being how it was in the early 2000s, but yes with the upscaling and smoothing it does look identical or near identical to the arcade version. Although the files sizes of arcade are much much smaller like 25mb compared to a 400-700mb iso

Oh I don't mind about Air Rescue, I just tried to do a full test of each board, and in a way is shows which boards are running better. Which may also be a throwback to the time, as some board drivers weren't fully emulated back in 2003 or 2010 even. 

Like the Model 2 stuff, there was a great model 2 emulator, and his code ended up going  into Mame or he helped them, but I don't know if they even have it running to the speed that his standalone emulator was running. And heard rumours he moved on to work for Sega.

I had no idea on Segasonic, I will avoid playing that until the update :) thank you

When you say Sega STV, do you mean the saturn ports of those games? Or Yabause can run the STV arcade roms?

I know there is a fork of Kronos that can run STV arcade roms, but when I tried in the Yabause xtreme core it just came up with the music loading screen/Saturn dashboard. So I just assumed it wasn't able to in this core?

Oh Waverunner is a Model 2 game; and the one you're thinking of is Waverunner GP which is the Naomi based sequel. :)

Btw is there any chance of a port for the Demul emulator? I read that it can emulate Gaelco stuff and also Hikaru stuff, I am most interested in Radikal Bikers!

Also are any Naomi 2 games up and running on the flycast core? I know they added support to the flycast android app earlier this year and have Naomi 2 up and running on that, but couldn't get anything to boot from the libretro core.

Thank you for the tip, I will try Star Wars Acade and Prop cycle on Mame 2022 :) I will also have a randomised go at trying some other games on that core.

The 2014 low profile definitely piques my interest!! By low profile, does that mean it has a lot of stuff cut out so it can be optimised for the arcade stuff?
