### ISSUE TITLE
Dreamcast VMU not working

### ISSUE THREAD

**Issue by AntiFly** [KMFDManic/NESC-SNESC-Modifications#199]
i am on current retroarch181 with current FLYCAST !

The Dreamcast VMU is not working anymore. 
I am not able to reset Memoryslots. If i do so, the slot gets inaccessible, data could not be written error and the slot is crap.
could you check on that please?

cheers

offtopic notice:
* metal slug 6 automswave is still not loading. (it just loads the vmu).

**Comment by AntiFly** [comment]
ive tried all slots, so all slots gone now for me, system tell me no memory card available.
how can i fix this ?

oO

**Comment by AntiFly** [comment]
All Slots could be repaired using Reicast instead of Flycast ....

**Comment by KMFDManic** [comment]
I am gonna email you on the Metal Slug 6 and other such things.  Did you sort the GB issue out yet?

**Comment by KMFDManic** [comment]
Look inside your saves folder, for vmu, you will notice an additional file that can be deleted, that may have gone corrupt.  This can occur from an improper shutdown, etc.

**Comment by AntiFly** [comment]
what do you mean with GB issue ?

**Comment by KMFDManic** [comment]
@AntiFly Was referring to the email you sent about Game Boy having glitches and how to fix it.  As far as the VMU, deleting the dc_nvmem.bin, which sometimes goes corrupt, will help get back on track on the VMU.  I will be changing it to work with Flycast Xtreme in the future, since you should be good to go on that Core once I provide you with the Updates Fix Files!

**Comment by KMFDManic** [comment]
@AntiFly Keep me posted if you continue to have any other issues:)
