### ISSUE TITLE
Amiga Core does work not as expected

### ISSUE THREAD

**Issue by AntiFly** [KMFDManic/NESC-SNESC-Modifications#210]
### Step 1: Describe your setup:

  * hakchi2 CE version: 3.8
  * RetroArch used (filename): /bin/uae4arm /var/games/CLV-S-YKVOC/Agony.uae
  * hmod(s) used by the game you are having problems with (filenames): _km_uae4arm.hmod / _km_bios_p-uae_whdload /
_km_auto_uae / _km_p-uae xtreme
  
### Step 2: Describe the problem:
  
I updated my system from scratch (factory reset and then 3.8 + hmods)
Got the issue that i can not load Agony (Agony.uae) anymore, with recent core i have used (2019-10-25) this was working.
This seems all the way no more working with .uae files anymore. 
How can I play them now ?

affected .uae games:
- Agony
- Apano Sin
- Chaos Engine
- RuffNTumble
- Uridium2
- Yo!Joe!
- Zool

I also updated my bios files for the cd32 support as well, but this should not affect this behavior.
.HDF files are loading just fine with /bin/puae.

please advise ;)
br

**Comment by AntiFly** [comment]
so agony is at least running with puae if i just put the .hdf instead of .uae loading.
Chaos Engine gives me an error about: This installed program requires at least a MC68020 CPU!. ??

**Comment by AntiFly** [comment]
so I am not able to run /bin/uae4arm.
there must be something changed i miss here ?
thanks for help

**Comment by KMFDManic** [comment]
@AntiFly It will be on my todo list, to look into what is causing conflicts with uae4arm.  While it is mostly unnecessary on the Minis for us, with the updated P-UAE, it would still be nice to have as a back-up plan!

**Comment by AntiFly** [comment]
@KMFDManic 
ye but for those games it is just not possible to play them otherwise we can load the game with the other core ;)
they are currently not usable.
br

**Comment by AntiFly** [comment]
Hi mate, any update on this, I would love to add the and play the games in the future again ;)
br

**Comment by KMFDManic** [comment]
@AntiFly In further testing, UAE4ARM is not a happy solution for most Amiga Games, due to the "horrific sound quality" and other issues relative to using that specific Core.  Any games you cannot run, let me know, specifically.  And, I will help you run them.  Note, if you add this little bit to your game names, such as Chaos Engine AGA.hdf, that will FORCE it to use the higher CPU.  Most games run fine on A600.  But, ones like Chaos Engine, require A1200 AKA AGA mode activate to run!  I did successfully get UAE4ARM working to a degree.  But, I immediately went back to P-UAE Xtreme, as games were far more playable there!  Just keep me posted on any you are still suck with.  And, feel free to send a message on Discord, or here, anytime!  I have other WIP Performance/Speed stuff, too, as well as a further Updated Amiga Core!  You should be absolutely fine on Amiga, once you have better setup as far as what should be going with P-UAE:)  UAE4ARM, sounds like freddy krueger scratching on a chalk board, making the games far less enjoyable, hehe:)
