### ISSUE TITLE
New Dosbox-Pure core fails to load

### ISSUE THREAD

**Issue by Wilmatron** [KMFDManic/NESC-SNESC-Modifications#217]
I don't know if it's just me but I cannot get the new Dosbox-Pure core to load, either by launching a game via UI (with the default command line values) or loading the core through Retroarch directly (displays no core bottom left of the Retroarch UI as opposed to the core name etc). This core is part of the Xtreme set on the mod store. The other two cores (dosbox and dosbox-svn) both load fine... is there a known issue?

I'm fairly familiar with Dosbox and have been using the new pure core on a Windows platform. Have tried launching from .exe and .dosz to no avail.

It's looking likely that it's a core problem though as I can't load the core into Retroarch prior to loading content. It's like it can't find the core...no core loaded etc. Also tried a simple uninstall and reinstall of the mod and changing the command line around by dropping km_ etc. No deal.

I'm on Retroarch 1.9.0 with the latest Hakchi and Dosbox Xtreme set. Many thanks.

**Comment by KMFDManic** [comment]
I did a retest of the Core, and it loaded and worked fine.  Make sure you are grabbing latest ones from Modules, KMFD Mod Hub.  1.9.0 RetroArch can sometimes have install conflicts, depending on whether or not you previously used an older older setup.  In these cases, the best way to properly update is to do kernel uninstall, install/repair, reinstall retroarch/cores/bios, resynch or reexport games.  

If you are on MD or SNES Classic, the Core should run fine.  If on NESC, then the necessary libraries to run the Core may be insufficient.  But, luckily, you can use an SNES Kernel, and then it would override the problem and the Core would work fine, in that case.  I have not personally tested THIS one on NESC.  But, it worked fine on my tests of MD and SNES, and a few others' tests, too.  My test was running game from Main UI, as well as Open RetroArch, have NO content loaded, and simply open core, choose dosbox pure, it opened fine, and loaded content with it, also loaded fine.

**Comment by Wilmatron** [comment]
Thanks for the update Kyland.

I'm on a Nesc. It would be interesting to find out if others on a Nesc also have this issue.

I'll try a full uninstall and reinstall of everything like you've suggested as I had come from Retroarch 1.8.4 to 1.9.0 quite recently.

If all else fails what do you mean by a "Using a SNES Kernel" on Nesc? How would I pull that one off?

Cheers,
Dave

**Comment by KMFDManic** [comment]
I would suspect it primarily works on SNES Kernels, then.  You can do a quick test, simply go to your USB, and in the hakchi folder, create this directory.  hakchi/firmware/ and you just need to copy and paste any SNES firmware into the firmware directory.  I will give you an example video of when I played around with it before.  This trick will also make LudicrousN64 Xtreme work for you!  That one doesnt work on NESC, either!  One thing to note, I run my directories a little differently.  So, I usually have hakchi/games and hakchi/firmware.  But, yours may be like hakchi/games/snes-us, etc  whichever firmware you use, you should rename the region to reflect that.  Once you try it, you will see what I mean.  If you want to do a simple test, just to confirm firmware works, you can temporarily cut and paste ALL games folder out of hakchi/games, so that it is simply hakchi/games with NOTHING in it at all.  And, then hakchi/firmware, with just the one firmware in it.  It would be exactly like in my video, and you would see custom games from that kernel!  The moment you add one single game, custom games go away, and you will still be on that kernel, though.  Once you get onto an SNES Kernel, you will see it is way better than the NES Kernel!  Plus, you can use those nifty Canoe Borders, and even add SNES games, use them with the Canoe emulator, rewind, etc, all that fun stuff.

https://www.youtube.com/watch?v=GL5pDvLoXEI

**Comment by Wilmatron** [comment]
Hi Kyland,

I did some testing this evening and to confirm; the SNESc Kernel fixed the issue I had loading the dosbox-pure core. Thanks for setting me on the right path.

Out of interest, I noticed when switching to the SNES firmware that the thumbnails hack I applied to my NESC no longer works. When switching back to NES firmware this is fine.

That being the case, is it necessary to install some of the mods again via the mod store? It's strange because when using the SNES firmware I can still load Retroarch and use other downloaded cores without any issues...so maybe it's picky..? Will updating/downloading new mods in the future prove to be troublesome?

**Comment by KMFDManic** [comment]
@Wilmatron Generally, the no thumbnails hack can have oddball issues, depending on kernel and setup.  It may be updated, accordingly, with a fix or such in the near future.  Otherwise, thanks for your feedback.  The current Cores that require MD or SNES Kernel are Glupen Xtreme, LudicrousN64 Xtreme, DOSBox Pure.  When I get time, I will try to debug these 3, and see what is causing them to non-load on the NESC, and possibly get them hard code fixed up, dependency wise:)  Thanks again, feel free to bump anytime you want to continue this feed!  And, be sure to enjoy the amazing DOSBox Pure Core.  My Tutorial is on YouTube, if you needed a few pointers.  But, I have a feeling you already got things covered:)
