### ISSUE TITLE
Still no Source Code?

### ISSUE THREAD

**Issue by Wiimpathy** [KMFDManic/NESC-SNESC-Modifications#218]
Can you share your modified cores source code please?

Sharing knowledge is always a benefit to all. There are many reasons for providing the source.
Freedom, other developpers improving the code, some kind of virtuous circle (you take from open source projects so you give a bit  in return), etc...

I can get the lazyness reason for keeping the code too. But some diff files are also welcome.

**Comment by KMFDManic** [comment]
@Wiimpathy You may be a little late to the party.  But, after you read this little synopsis of the drama that we have had in our scene, then read the rest of my response:)

https://gist.github.com/DanTheMan827/33f6ee39977dfe6ed33c8f13a9a230f6

In any case, there was a period where the other group intentionally went out of their way to prevent me from doing what I do.  Even taking a Release of mine, reposting it as theirs, and attempting to ban me from the Scene.  I would get "fake alt" accounts PMing me quite often, asking about source, compiling, and so on.  It was difficult to know who was legit or just playing mind games.  So, a few of us took a stand against this behavior.  And, the public became more aware of what they had done to us and others.  One of the last things they had done was delete ALL chat logs from their Discord Server, which covered up a lot of the harrassment, drama, etc.  But, me, personally...I absolutely refuse to allow even a hint of bullying to occur.  So, I took a stand, did a video, and eventually...things settled down.  But, through all that, source was never truly an issue.  When bullies ask about source, it isn't the same as a person showing respect when wondering about source.  

IE:  I have had source available for a few years on the Cores that I most make changes to, such as:

https://github.com/KMFDManic/mame2003-xtreme

And, because Nintendo 64 Emulation wasn't very good for us on lower spec, I tried to do what I could to best optimize things, and retooled it as LudicrousN64 Xtreme:

https://github.com/KMFDManic/LudicrousN64-Xtreme

When all this drama had originated, my exact idea was a very simple one.  I communicate with other developers in Libretro, and/or in our Scene..And, things that need fixed up, are looked into.  Something like Commodore 64 not having a viable mapping keyboard to controller issue, I brought up to fr500 and r-type.  And, r-type helped with a temp alternative, til fr500 pushed changes into the context of official Libretro source, and now...many PC Cores have keyboard to controller mapping!  

I show videos of WIP, changes, fix-ups, etc.  And, then with each new Release, I push these Built Cores out for MD/SNES/NES/PSC.  Some on other platforms ask for help, and I have helped when there is respect shown.  Like, someone wanted to run Virtua Fighter on RetroPie 4, which runs AWESOME with MAME 2003 Xtreme:)  

Most source I use is Libretro Official, as I try to get them to add the "harmonious" changes to the Cores, so all benefit.  But, some other ones like MAME 2003 Xtreme, aren't as compliant with what Libretro normally goes for...So, they are their own thing.  Hence, the Xtreme.  These are not as stable as the normal Libretro Cores, as I push for performance and speed, versus accuracy.  And, Libretro has generally been more about accuracy, as are MOST people who want to emulate these games:)

You can see most source I am using, simply by going to what I have already posted:

https://github.com/KMFDManic?tab=repositories

Other changes with work in conjunction with the Cores go directly into hakchi, our front end for helping run RetroArch/Cores, on the Minis.  And, of course, we do some bash scripts, custom OverClock scripts, and so on.  So, kind of some duct tape fixes, or permanent fixes, depending on any given scenario in time.

In the end, those who disrespected us or tried to remove our ability from posting Releases in THIS particular Scene, is why drama had ever occurred to begin with.  If people were a bit nicer, instead of bullying, things could have gone quite a bit differently.  But, as it stands, we have a huge fracture in this Scene.  But, many many hundreds to thousands of users have shown amazing support, which is why we keep going and pushing out more and more kickass stuff, each and every new Release!

Thanks for reading!  Anything you truly need help with, just let me know!  I see you are into FBA, for example, of which @dinkc64 is a total awesome mate to talk to, when it comes to that stuff!

**Comment by Wiimpathy** [comment]
Ok. Not really interested in drama. But I guess it's sadly the standard behaviour when a couple of males fight for fame, property or other vain reasons. Even with open source projects, sigh...

Only interested in technical details. I've already asked politely but I'll reiterate. Where are the source codes of what you call 'snes9x2010_xtreme' and fceumm_xtreme? Are they the same as https://github.com/KMFDManic/snes9x2010 and https://github.com/KMFDManic/libretro-fceumm?
If not, do you mind sharing your modifications please?
The former doesn't seem to contain any specific classic platform commit.

The goal is just to compile a few cores myself if your mods adds some value compared with the official libretro cores. 
Don't be afraid, no release with my name in bold, I don't give a damn.
Thanks.

**Comment by KMFDManic** [comment]
@Wiimpathy These 2 Specific Cores are using the source that you linked to.  But, they are bash script set to use overclock to help with games, such as Gradius 3, Contra Force, and so on.

```#!/bin/sh
overclock(){
  local cpufreq="/sys/devices/system/cpu/cpu0/cpufreq"
  [ -z "$1" ] || cfg_cur_freq="$1"
  local freq="$cpufreq/cpuinfo_${cfg_cur_freq}_freq"
  if ! [ -f "$freq" ]; then
    cfg_cur_freq="max"
    freq="$cpufreq/cpuinfo_${cfg_cur_freq}_freq"
  fi
  cat "$freq" > "$cpufreq/scaling_max_freq"
  echo "current freq: $(cat "$cpufreq/scaling_cur_freq")"
  echo "current temp: $(hwmon)"
}```

Which is another hmod shared in my Release, which properly activates the better performance speed on these 2 Cores.  Others, such as MAME 2003 Xtreme, we were able to get speed up fixes directly into that Core.  Not as easy with fceumm/snes9x.  I usually recommend people use standard fceumm or 9x, since overclock will NOT work for everyone.

**Comment by KMFDManic** [comment]
@Wiimpathy Last thing, for now.  If you are looking for improvements, as far as "lower spec" hardware...I assume you are running stuff on Wii?  Not sure how well N64 runs there, since I haven't tried it.  But, if you wanna try this Core that I optimized to as best work with lower spec hardwares as possible, this may do the trick.  Try a game, such as Cruis'n Exotica with it.  You can adjust in Core Options, Turbo Boost and/or OverClock.  Using Turbo Boost X1 can help boost a bunch of games that may otherwise be slow for you, if Wii has N64 issues.  Otherwise, let me know if any other Cores don't handle well enough for you on whichever platform you do use.  

https://github.com/KMFDManic/LudicrousN64-Xtreme
