### ISSUE TITLE
_km_fbalpha_2012_neogeo and _km_bios_neogeo_unibios_fba2012+req

### ISSUE THREAD

**Issue by creamstick** [KMFDManic/NESC-SNESC-Modifications#26]
Just a quick question, are these supposed to work together, or is it only _km_bios_neogeo_mame2010+req that works with the cut-down NEOGEO only FBA core?

The blurb on the unibios says it works with the command line /bin/neo which would indicate that it does work with fbalpha_2012_neogeo, but even changing the /bin/zip to /bin/neo and adding NEO-GEO (after a space) to the end of the command line, nothing happens on the SNES Mini when I try to start a game, except a black screen and return to the SNES Mini menu.

The unibios works great with the full FBA2012 and FBA2016.

Thanks!

**Comment by KMFDManic** [comment]
Thank you for your input on the "inability" to use Unibios with FBA 2012 - NEOGEO.  Unfortunately, the FBA 2012 - NEO Variant is built on minimal code, so as to be conveniently small.  As a result, in transition, it lost ability to read the Unibios portion of the NEOGEO Bios that I modified.  It also cannot run 7z, like it's brother and sister FBA 2012/2016.  I will Update the ReadMe to reflect that Unibios should only be used with FBA 2012/2016.  Thanks again!

**Comment by creamstick** [comment]
I have discovered that if you go into the Retroarch settings, you can enable the Unibios in the NEOGEO variant.

Install _km_bios_neogeo_mame2010+req - not the Unibios.

Load up a NEO GEO game, Select & Start into the Retroarch settings. o into Quick Menu/Options and you'll see Neo Geo UniBIOS - disabled. Change this to enabled, back out to the game, back to the SNES Mini menu, open up the game again an BAM - Unibios. This persists after a shutdown as well.

**Comment by KMFDManic** [comment]
@creamstick, I actually forgot about that option, hehe.  Was so busy with other Updates, it escaped me.  But, yes, that is true.  I will update the ReadMe to reflect that, of course!  Thanks for the reminder.

**Comment by creamstick** [comment]
Hi! Just noticed you've put the fba2012_neogeo fix for the unibios in the wrong section. Here's how it works:

install _km_fbalpha_2012_neogeo and _km_bios_neogeo_mame2010+req

Load up a NEO GEO game, Select & Start into the Retroarch settings. Go into Quick Menu/Options and you'll see Neo Geo UniBIOS - disabled. Change this to enabled, back out to the game, back to the SNES Mini menu, open up the game again an BAM - Unibios. This persists after a shutdown as well.

It doesn't work with _km_bios_neogeo_unibios_fba2012+req, only _km_bios_neogeo_mame2010+req

Funnily enough, there is no unibios setting when using Mame 2010 and _km_bios_neogeo_mame2010+req

Cheers!!

**Comment by KMFDManic** [comment]
@creamstick Thanks so much for letting me know.  I will get this adjusted sometime today when I do another Core update:)

**Comment by boufftout** [comment]
Hello guys ! I need your help... I have some issues with few neo geo roms... Most of them work just fine but some of them like Pulstar or Street Hopps are unable to run with any core I have ( core fba, unibios v3.2 for neo geo). I tried as well to put the bios ( old and new) into the game folder but there is no change.... I don't understand and don't know what else to try.... if anyone can give a hand that would be nice....thanks

**Comment by KMFDManic** [comment]
@creamstick I will need to revise the ReadMe files and rename the Bios.  I have set things up a few different ways over the last year, for Old/New Arrangements.  Uni-Bios gets very finicky in some cases, and has garbled graphics for some games (Ironclad was one that I just HAD to have running with proper graphics!).  The way I ended up setting them up bypassed the garbled graphics.  So, I will rename them, and adjust the ReadMe files.  I truly appreciate your time in testing things out!  It means a lot!

@boufftout Given you have the correct Arcade Core + Bios Combination, it pretty much remains to a few factors such as proper rom set, correct command line, and avoiding user-end errors, such as too many games per folder, and so on!  You will have the best success with FBA 2016, plus the Bios Install for that, since a vast majority of the rom sets you will find laying about, pretty much covers that vein.  If you still have issues, let me know!  I would suggest trying just Metal Slug 1, FBA 2016 and the _km_bios_neogeo_mame2010+req, just to test the waters.  I will do another Neo-Geo Bios Overview, to better explain things for the uninitiated.
