### ISSUE TITLE
(MAME2000) Missing core input remapping feature

### ISSUE THREAD

**Issue by bankaiprimera** [KMFDManic/NESC-SNESC-Modifications#29]
Mame2000 is missing core input remapping feature, which is accessible from the quick menu’s “controls” submenu. It lets you move the core’s buttons around on the retropad.

(Nearly) all other RetroArch cores do offer this feature and it is sorely missed in mame2000.

For example Mortal Kombat's default controls are horrible, would be awesome to be able to configure them using this feature.

**UPDATE:** the latest commit should be able to do this..! Any chance of you updating the SNES MAME2000 to this any time soon? Thanks for all your hard work thusfar!

sourcelink: https://github.com/libretro/mame2000-libretro/issues/54#issuecomment-341143268

**Comment by KMFDManic** [comment]
With the latest MAME 2003 Updates I have added, Mortal Kombat has better sound, and you can easily map the controls using R2, and this video, as a brief tutorial.  MAME 2000, I compiled latest changes, and they didn't work on NESC/SNESC.  Some Cores lost compatibility with more recent changes.  But, MAME 2003 is still going very strong!  Here is my tutorial!  Having fixed sound in Midway Games like Mortal Kombat and NBA Jam, also helps with overall speed of the games!

https://www.youtube.com/watch?v=jjwpW9j65TM

I will be posting yet another MAME 2003 Update, soon, which I just tested with MK & NBA Jam, to great success...It will be posted by tomorrow am:)

**Comment by bankaiprimera** [comment]
Thanks for your reply and all your great updates! Two things I'd like to add:

1. I can't enter the MAME menu through the R2 button.. because I don't have a classic controller and there's no way of altering the hotkey for it. You _have_ to have a classic controller in order to enter the menu.

2. mame2000 (3mb) is more light-weight than mame2003 (6mb), which is great because of the serious size restrictions. Also, because it's less accurate, it's faster in some games resulting in a smoother gameplay. For example Outrun and Mortal Kombat 1 run without a hitch on mame2000 and they lag on mame2003.

So it would still be totally awesome to be able to change the controls of mame2000 through through the quickmenu.. but it seems it can't be done?

**Comment by bankaiprimera** [comment]
User @hunterk at the retroarch forum said he just added the feauture to the mame2000 core..! Maybe you could check it out and merge it?
https://forums.libretro.com/t/snes-mini-per-core-config-files/12876/7

Would be so awesome!

**Comment by KMFDManic** [comment]
@bankaiprimera This sort of sucks.  But, sometimes, certain Cores get Broken, as they Update.  I grabbed the latest MAME 2000, and it didn't function on the NESC/SNESC  Some other Cores have the same issue.  They generally work great on PC, of course!  But, several simply do not work on NESC/SNESC  MAME 2016 is another like this.  The latest Code is just not compatible with our Set-Up.  It would need Compiled in a different way to have a shot at working.  I will still look into it.  But, the one I compiled, is not working, unfortunately.  Many Cores, I can Compile, just fine, and they work:)  Others, are more stubborn, and no longer work.  Mupen, Glupen, are two others that got completely broken for us with the drastic Coding Changes.  Again, I will keep 2000 in mind, and see if I can get the Coding to compile right for our needs.

**Comment by KMFDManic** [comment]
@bankaiprimera, I will take another look into MAME 2000 over the next day or two, and see if I can figure out a way to improve mapping for you.

**Comment by bankaiprimera** [comment]
Thanks for your efforts @KMFDManic I really appreciate it!

**Comment by KMFDManic** [comment]
@bankaiprimera One workaround you may be able to use, for input binding, is this...But, beware, if you do it incorrectly, you can break your ability to open up RetroArch options.  You can generally uninstall/reinstall RetroArch to fix this (There are some cases where a complete hakchi2 uninstall is necessary, if you really screw things up.  I would also advise using FTP to back-up your RetroArch Config Files, as I ALWAYS do before I mess with anything:)  If you need help doing that, let me know!  But, you can easily drag and replace the back-up as you play with the adjustments, per below:)  This will negate your need to uninstall Hakchi2, if you really goof it up.  I am gonna do a video about this, sometime in next couple days:)  I have used this workaround with other Cores.  It just isn't exactly user-friendly, due to the ease of breaking RetroArch Control Config.  But, it has worked for me:)

Anyways, RetroArch Settings, Input, User 1 KeyBinds, Bind All, etc.  Manually map, or Bind All.  You can ignore keys that do not need to be mapped.  It greatly helps to know what keys are already binded, being that you are using a standard controller!  You can test this on the fly!  So, it may take just a little bit of trial and error.  

Main thing is, this should remedy your Control Issues.  You have likely been attempting them from Controls, which is not a good place to do it, in this case.  Just proceed with caution, as...even, me, in my personal tests, have accidentally broken the RetroArch in my first attempt:)  But, I worked out super easy ways to fix it, as displayed above!  (uninstall RetroArch/reinstall RetroArch; Replace RetroArch Config with Back-Up via FTP; Worst case scenario---Uninstall Hakchi2.  

Good luck!  Hope this helps!

P.S.  I will still work on getting Updated MAME 2000 working, so that you can use the Updated Mapping method!

**Comment by KMFDManic** [comment]
@bankaiprimera Alternatively, you can also manually make a controller configuration file and throw it into the mix via FTP.  I will better clarify this when I have a chance to.

**Comment by bankaiprimera** [comment]
Thanks for your trouble man. I tried changing all default controls through input, but I ended up having to reset everything. So, would be great if there’s another way. 

Ps. Thanks for the custom picodrive 32x only core!

**Comment by bankaiprimera** [comment]
Update: https://github.com/libretro/mame2000-libretro/issues/54#issuecomment-346072285

There's a new core update which is supposed to fix the issue! Could you maybe compile it using your custom parameters?

**Comment by KMFDManic** [comment]
@bankaiprimera I tried the New Core Update.  But, it didn't function on the NESC/SNESC.  I may need to possibly compile it a different way.  As mentioned before, some Cores, with coding changes...no longer work in our Environment.  But, I will try to prioritize MAME 2000, as well as SNES 2002.  Both of these Cores have their Pluses:)

**Comment by KMFDManic** [comment]
@bankaiprimera I am gonna try to make a generic controller config file that should help with your problem. It should effectively help with all of the MAME Cores.  And, you can still use MAME Options with SNES Controller.  It will be a 2 button shortcut, rather than R2, when you remap.

**Comment by bankaiprimera** [comment]
That would be great @KMFDManic ! Thanks for your time.

**Comment by KMFDManic** [comment]
@bankaiprimera Ironically, MAME 2010 is also missing the configuration.  MAME 2003 is the best for this stuff.  I did test it on SNES Controller, and MAME Options do work fine.  I just changed input from R2 to R1, changed what I wanted to change, then changed it back.  Have you tried running OutRun, MK, etc on FBA 2016, or FBA 2012?

**Comment by bankaiprimera** [comment]
Mortal Kombat doesn't work on FBA unfortunately and it doesn't run fullspeed (has sound issues) on mame2003. That's why I really want mame2000 to work with control mapping options 👍 

Didn't it work to remap the "mame menu" controls to a different button than R2 in mame2000? Because that _would_ be a great workaround!

**Comment by KMFDManic** [comment]
@bankaiprimera There are a few options I can try to work out.  Two different ways of doing custom controller configs, that will need tested.  MAME 2000 may need compiled in a different environment, to properly work.  I was planning on doing an alternate set-up in the near future, to compensate for things like this.  

What is your take on the possibility of using USB-HOST, and running the amazing MK Trilogy for PS1?

**Comment by romadu** [comment]
Hi
Any update on the generic controller file for MAME, a two-button shortcut instead of R2, or the step-by-step for changing from R2 to R1 in a persistent manner? I’d really like to have either two button shortcut or change from R2 baked into my RetroArch configuration so that a classic controller isn’t needed to access the core configuration menu. Thanks very much for tour help.

**Comment by KMFDManic** [comment]
@romadu @bankaiprimera I was incredibly busy with other projects, work, and such, that this got sidetracked,  I apologize:)  In any case, I was able to quite easily remap MAME 2000, using the SNES Controller, as well as any other controller that I connected to it (clovercon helps with the generic ones!).  In any case, here is how to do it, very easily...

1.  select+start, obviously, to pull up RetroArch Options
2.  Settings
3.  Input
4.  Input User 1 OR 2 Binds
5.  Select the button you want to change, then tap A, then tap the button you want it changed to!
6.  Keep in mind, if your B button is BACK in the RetroArch Options, and you reconfigure it to Y, Y will then become your back button!
7.  Avoid changing select+start, as then you will end up breaking your ability to use RetroArch Options!  And, you will need to uninstall RetroArch, then reinstall it!
8.  If you screw up, simply choose User 1 OR 2 Bind Default ALL!  
9.  Just back out to quick settings, then resume the game, to test things:)
10.  If satisifed with the mapping, leave it alone:)  It should save.  I powered off the system and back on and it worked absolutely perfectly.  
11.  Use Bind Default ALL when you want to revert.  And, do not forget, if you truly screw things up...Just uninstall RetroArch/Reinstall RetroArch:)  

This should do the trick:)  It also works with pretty much every other Core:)  

Closing this issue, as I had no problem whatsoever with doing this with Mortal Kombat, Outrun, and Journey, amongst several other test games:)  Hope this helps, guys!

**Comment by romadu** [comment]
Thanks for your help.

I've found a partial solution to access the core menu and turn on cheats
using the standard SNES controller.

After this change, pressing R will open the core menu, which allows access
to Cheats in Mame 2003

In Retroarch game press Select+Start for Retroarch menu

Either a) Quick Menu, Controls, User 1 Button 8 : R2 button (trigger) ---
with d-pad, change setting to R button (shoulder)
B button to go back, then Resume
Press R to access core menu

Or b) Settings, Input, Input User 1 Binds, User 1 Button 8 --- normally set
to 7
Press A and the pop-up will confirm that this is the setting for R2 button
(trigger) , then press R to set the button --- now set to 5
B to go back a few menu levels, Quick Menu, Resume
Press R to access core menu

However, pressing R at any time will access this menu. After changing
cheats or other settings, turn it off again if the game uses R.

This change doesn't persist on my machine, even after exiting the game and
restarting it, or starting another. However, I haven't found a way to
require a combination of keys, like Select+X or Select+R, so having it off
by default is better.

I tried Settings, Input, Input Hotkey Binds - Enable hotkeys --- changed to
Select
also in Input Hotkey Binds - Menu toggle --- changed to R

but this setting opens the Retroarch menu rather than the core menu

I haven't found a way to remap the 'access core menu' button from R2 to a
combination of Select+X or Select+R. I've just remapped R2 so that it's
function is activated by a different, single button press

It works for me. Thanks again for all your help and suggestions.

**Comment by KMFDManic** [comment]
@romadu This will be something I will still play around with to try to better.  But, the User 1 Binds have worked for me for any Cores that can reliably use a controller.  Only ones like Commodore 64, CPC Amstrad, etc, get a little finicky with stuff like this (USB-HOST is far superior, so you can use a real keyboard).  I was able to get keybind support in for Commodore 64, at least!  I may still toy with the idea of config files in HMOD format, so you can manually edit the controllers, such as select+x, etc, then just install the HMOD.

**Comment by KMFDManic** [comment]
@romadu @romadu I may have gotten mapping working for MAME 2000, and, I will be releasing an hmod, if it pans out.  If either of you do not mind, Let me know how you would like the controls remapped for MK.  I will do a template, then test:)

**Comment by romadu** [comment]
Hi

Thanks, that’s good news. Perhaps map Select+X.

Cheers

**Comment by KMFDManic** [comment]
@romadu @bankaiprimera I succeeded at mapping controls for MAME 2000.  I will be posting an HMOD to do this, in tomorrow's Update:)  I appreciate the patience.

**Comment by romadu** [comment]
That's great news. Does it also work for Mame2003, which supports cheats?

**Comment by bankaiprimera** [comment]
Thanks @KMFDManic! Controls should imo be like the snes version of MK:

Y = High Kick

B = Low Punch

A = Low Kick

X = High Kick

R = Block

L = Block

**Comment by KMFDManic** [comment]
You can do it for MOST Cores, using the HMOD I am including in Today's Update @romadu

**Comment by romadu** [comment]
Great news. I’m interested in remapping the core menu (for cheats, in game
options etc) from R2 to Select+X since SNES Classic controller does not
have R2 button.

**Comment by gingerbeardman** [comment]
@romadu a lot of people use [Wii Classic Controller Pro](https://en.wikipedia.org/wiki/Classic_Controller#Classic_Controller_Pro) with these RetroArch cores

**Comment by romadu** [comment]
Yes and many more don’t have access to Wii Classic controller. In response
to the question I was asked, if it’s possible to remap the buttons, that’s
how I plan to use the remapping function. :)

**Comment by KMFDManic** [comment]
@bankaiprimera @romadu Update posted:)  And, video of it in use.

https://youtu.be/UInJWOJt3Dk

Posted in my releases

https://github.com/KMFDManic/NESC-SNESC-Modifications/releases
