### ISSUE TITLE
[Request] Atari ST (or Amiga) core?

### ISSUE THREAD

**Issue by gingerbeardman** [KMFDManic/NESC-SNESC-Modifications#3]
I saw a mention where you said you might be able to add the Atari ST core. This would be awesome if possible! it was my teenage crush computer and I'd love to replay such classics as Sensible Soccer (the MD/SNES versions are watered down)

**Comment by KMFDManic** [comment]
Amiga will not be as easy to pull off.  But, Atari ST may still have a chance.  I did make a Core for it awhile back and can retest it with a newer compile to see if it has a chance of functioning in our Mini NES/SNES Environment.

**Comment by KMFDManic** [comment]
Status Update, RetroArch is updated to 1.6.7, so we may have better chances at more Cores!  I will see what I can do about getting something else going!  But, for now, we have SNES9x, and new RetroArch!  Enjoy:)  And, be sure to read my update on the Save State Fix!

**Comment by DJM75** [comment]
Atari ST and Amiga cores would be fantastic but I think the Mini (S)NES is too slow to run the Retroarch Amiga core. Anyway I would love to see Atari ST. Please KMFDManiac! ;)

**Comment by KMFDManic** [comment]
Update, had so many Cores to update! (Over 40+), that Atari ST got put on the back-burner for a little time.  I am going to take another stab at it, along with a few other Cores, over the weekend.  And, as far as 3DS, if you can email me a Core you currently use on the 3DS, we can proceed to try to get some you want updated for that.  You use Reddit?

**Comment by KMFDManic** [comment]
Same as the Sharp Core...This core is currently incompatible with the NES/SNES Classic, and would require some rewrite and recompiling of the code, unfortuately.  There are a good dozen+ Cores with similar issues, related to compatibility.  Doing such rewrite or compile can be as easy as a couple hours, or as hard as many, many hours.  I will still keep it in my longterm agenda!  I compiled the Core Correctly, have all Bios in place.  It simply does not function on the Mini NES/SNES, sadly!  But, it has a far better chance of working than the Sharp Core does.  I will still poke at it, when I am able to, between working on other Cores and related side-projects.

**Comment by gingerbeardman** [comment]
If you care to share details I'll dive into the code and see what I can do. Is about time I gave something back.

**Comment by KMFDManic** [comment]
There is actually something a little bigger I am going to be focusing on, and it will open up the NES/SNES to more possibilities.  I also want to run Intellivision:)  Atari ST, for now, is just incompatible.  There are many variables that come into play that can cause a Core to be incompatible.  Remember, these Cores were mainly designed to run on PC.  I am not entirely giving up on it.  But, like PSP/DS, I can only spend so much time attempting to get them to work, before working on ones that have more reasonable expectations.  This also directly parlays into issues, such as with MAME 2003, wherein we cannot properly run Midway/Bally Games, System 32 Games (Obviously, I was able to exploit, luckily...to get System 32 to function:), and so on.  But, the PC Counterparts (True Emulators the Cores are based upon), run them!  And, the bad thing here...even if Atari ST runs, no guarantee we will have controller support.  There are still quite a few things to get going.  But, I will definitely keep Atari ST as a potential candidate and look into it as much as I can.  It may involve rollback of the code, such as you originally suggested with FMSX!  But, now, even that isn't a huge matter...since I got BlueMSX going:)  Thanks so much for the feedback and the offer to help.  But, I truly do not want you to invest too much of your own personal time on something that may be incredibly difficult and complex to get working on the Mini NES/SNES, yet functions quite easily on PC.  If I can get the other stuff going, that I am tentatively planning on...there will be a lot more we can do in this Environment:)

**Comment by gingerbeardman** [comment]
Of course, no worries! You're the boss :)

**Comment by KMFDManic** [comment]
I have a whole set of things I am trying to get to and accomplish on the Mini NES/SNES.  One that I had put off for a little while due to other things was getting CHEATS to work with MAME.  I succeeded and will post that in my next update.  I always have something to work on, and it benefits us all if I get things going, in the end:)  Many people will be happy with the MAME Cheats Update!  But, Intellivision is another I want to hopefully get going, sometime this week, if it is technically possible to.  And, I will also try to get the Atari 800 Portion of the Atari 800 Core to work.  So far, just Atari 5200.  I will see about the other elements:)

**Comment by KMFDManic** [comment]
I played with ST again, for a few minutes yesterday.  I actually got the Core to load.  But, there is still an internal conflict somewhere.  I will continue to throw small tests at it, and hope for the best, whilst still working with other Cores.

**Comment by gingerbeardman** [comment]
Great, continued thanks

**Comment by KMFDManic** [comment]
Today's Update will include ability to run Atari 800 Games.  When you go into the Extras & Dependencies Folder you will see what I mean.  This is potentially how we will fix Hatari to run.  Due to the foreign environment, a config file will be needed to take into account the Bios.  I will post the Hatari Core to the set, as well, along with the Bios.  But, it will not work until we figure out a config file.

**Comment by gingerbeardman** [comment]
Great! I'm happy to help in any way.

**Comment by KMFDManic** [comment]
When you see how Atari 800 is handled, for now, at least...You will better understand the process we will need to potentially follow to grant Hatari true access to the Mini NES/SNES Environment.  I set it up in such a way, as to where we can "Test" for now.  Once things are better acclimated, scripting can be done to make it installable (Atari800/Hatari Wise).

**Comment by KMFDManic** [comment]
Updated Hatari to the Set, this Issue will now be deemed a WIP.  And, hopefully we can solve this conundrum.

**Comment by gingerbeardman** [comment]
Still not got my SNES mini back from Nintendo! Can't wait to check this out

**Comment by KMFDManic** [comment]
@gingerbeardman The only way Hatari will work, is with a modified Config File.  I do have a Config to work with.  It isn't priority, just yet, as I want to do a Video on Expandable Memory within next day or so.  But, being that you are a fan of Hatari, as well, you are welcome to work with me on the Config, whenever you are ready to.  And, a heads-up, I would not expect too much from even a working Core, in this case.  We may only be able to load a few formats or less.  Ones like STX may not work, at all.  It would be nice to get this going.  But, it pretty much rests in the Config of it all, at this point.  Then, hopefully, the games being able to load with said Config!

**Comment by gingerbeardman** [comment]
I'm happy to help when I can. 

Nintendo still be my SNES mini for repair. I guess right now they don't even have a replacement to send me?

**Comment by KMFDManic** [comment]
@gingerbeardman Hope you have a great xmas.  I am gonna have another go at ST.  Which PS1 Game did you need tested, again?

**Comment by gingerbeardman** [comment]
This one: https://www.gamefaqs.com/ps/566070-the-hanafuda-jarin-ko-chie/data

**Comment by KMFDManic** [comment]
U see I got PC-98 working more optimally, as well as with USB-HOST?  Your PS1 Game should be an easy test.

**Comment by KMFDManic** [comment]
Crossing my fingers for some Atari ST goodness, once I am caught up on other things,  My theory on other "stubborn" Cores, has worked out nicely as far as getting them to work, such as PC-98, BlueMSX, and even Atari 5200!  It is generally common knowledge that neither the Amiga or Atari ST Core are overly great, in comparison to some of the far more optimal ones we have become accustomed to.  But, even if one single game can run on ST, that will be success in my book:)  The Odyssey Core, only ran a few games, when doing that for NESC!  But, with USB-HOST, that now changes, with keyboard support!  I also have the Core that supports true Super Game Boy working!  But, the setup of it to actually load the SGB Games may be very tricky for our environment!  Anyways, this issue is now being closed, since even the guy who officially released Atari ST into the upstream, declared maybe he should not ever have!  But, I am still gonna keep poking at the dead horse, in hopes that it will stir as a New Year's Resolution!  I also hope to get the Hanafuda Game going!  At least there are many others!  Hopefully, some of those are at least suitable replacements, my friend:)  So, enjoy the Holidays, and thanks so much for your absolute continued support on my Github!  I have a ton more things to add!  I will let you know if I need any assistance testing, since you are such a valued asset in my Community now!

**Comment by gingerbeardman** [comment]
All the best to you!

**Comment by gingerbeardman** [comment]
Just putting this reference here for keeps http://forums.libretro.com/t/getting-started-with-hatari-atari-st-ste-tt-falcon-emulation/13237

**Comment by KMFDManic** [comment]
ST and Super Game Boy and helping others run Doom are next objectives.  Wish Hanafuda worked:(

**Comment by gingerbeardman** [comment]
Hanafuda works on my N3DS (as cue/bin) so I'll look into running it like that when I can
