### ISSUE TITLE
Neo Geo roms issues 

### ISSUE THREAD

**Issue by boufftout** [KMFDManic/NESC-SNESC-Modifications#32]
Hello guys ! I need your help... I have some issues with few neo geo roms... Most of them work just fine but some of them like Pulstar or Street Hopps are unable to run with any core I have ( core fba, unibios v3.2 for neo geo). I tried as well to put the bios ( old and new) into the game folder but there is no change.... I don't understand and don't know what else to try.... if anyone can give a hand that would be nice....thanks

**Comment by KMFDManic** [comment]
@boufftout Worry not, I get your messages, whether or not the Issues are closed or open:)  In any case, I will repost this message from the Closed Issue.

@creamstick I will need to revise the ReadMe files and rename the Bios. I have set things up a few different ways over the last year, for Old/New Arrangements. Uni-Bios gets very finicky in some cases, and has garbled graphics for some games (Ironclad was one that I just HAD to have running with proper graphics!). The way I ended up setting them up bypassed the garbled graphics. So, I will rename them, and adjust the ReadMe files. I truly appreciate your time in testing things out! It means a lot!

@boufftout Given you have the correct Arcade Core + Bios Combination, it pretty much remains to a few factors such as proper rom set, correct command line, and avoiding user-end errors, such as too many games per folder, and so on! You will have the best success with FBA 2016, plus the Bios Install for that, since a vast majority of the rom sets you will find laying about, pretty much covers that vein. If you still have issues, let me know! I would suggest trying just Metal Slug 1, FBA 2016 and the _km_bios_neogeo_mame2010+req, just to test the waters. I will do another Neo-Geo Bios Overview, to better explain things for the uninitiated.

**Comment by creamstick** [comment]
I've just found that the fba2012_neogeo in the latest release doesn't work, so your problem may be related as both of the games you mentioned work fine with the previous release. NEO GEO games don't usually need to be from a specific romset (except for bootlegs), as the ROMs don't change between versions.

**Comment by creamstick** [comment]
@KMFDManic No worries, happy to help! By the way, as above the fba2012_neogeo in the last set (the one before today's) isn't working.

**Comment by boufftout** [comment]
Thanks a bunch for your advice, I installed the différent cores and followed your instruction, yet the two games street hoops and pulstar couldn't be launched again...I only get a black screen for a couple of seconds and then it comes back to  the menu screen.. I must confess I'm getting desperate about this issues...why some games like metal slug, magician lord, Nam 75, super sidekicks 3, last resort and viewpoint would work and not a few ones(pulstar, street hoops)...Could you test those 2 games on your snes and give me your feedback? Thanks a lot for your help

**Comment by KMFDManic** [comment]
@boufftout I will test these out tomorrow, as well as advise you on the best course of action:)

**Comment by KMFDManic** [comment]
@creamstick I didn't have time to get to NEO-GEO for Today's Core Update.  But, I will try to revise it by Tomorrow/Thurs!  As far as NEO-GEO being "specific"...Many games do not change much over the years, if at all.  But, games such as Metal Slug 1, as an example, has changed.  So, using the rom set from MAME 2003, would not work in, say, FBA 2016.  The md5 Hash-Checks do not match.  I have the SAME Double Dragon Rom Set on MAME 2003, MAME 2010, MAME 2014, FBA 2012, FBA 2016, and it has worked...due to it really not changing and being "pretty much" the same Rom Set:)  Others, like Moon Patrol, get changed to be more Accurate to the Arcade Version, and an "older" rom set would not be applicable to working in a newer MAME.  You may find many NEO-GEO that work on both MAME 2003/FBA 2016.  But, Metal Slug is definitely one that does not:)  When I revise the NEO-GEO Portion, I will also do a video on the Bios Overview, as well as general things to watch for.  Thanks again, and I credited you in the ReadMe for FBA2012-NEO.  I will get things going again for the next Update!

**Comment by creamstick** [comment]
@KMFDManic Nice one! Cheers!!

@boufftout They might just be bad roms, try a different source. I've been messing around with NEO GEO stuff all day, and both games you mentioned are working perfectly with FBA2012, FBA2012_NEOGEO and FBA2016. Pulstar also works perfectly with MAME 2003.

**Comment by boufftout** [comment]
Good morning ! Thanks for your answer...So I installed the cores as you mentionned, tried and found a another pulstar rom from a different source, but It appeared to be the same(same size anyway) and I still encounter the same issue, the game doesnt start.... 
I must tell you that the neo geo games that work properly don't have the bios.zip in the game folder (snes_game) in hackchi and have the fba in the argument command Line. 
I wonder now if the games I can't run need another argument such as /fba 2012/ or another instead of /fba/ that runs most of the neo geo games I have. So could you please check for Pulstar and Street Hoop and tell me what command argument line do you have.(assuming that the real problem is here🤔). 
Regards.

**Comment by creamstick** [comment]
If you're only running NEO GEO games, all you need is _km_fbalpha2012_neogeo and _km_bios_neogeo_mame2010+req  installed. Your command line should start /bin/neo

At the end of the command line, put a space, then NEO-GEO

For FBA2016, install _km_fbalpha_2016 and _km_bios_neogeo_unibios_fba2012+req. Your command line should start /bin/fba and end that same as above.

Don't install more than one neogeo bios at a time, they will cancel each other out.

**Comment by boufftout** [comment]
Thank you creamstick  for your help...but the bad news is that there's no change, I'm still unable to run those fucking games that are street Hoop pulstar and some other...I followed stem by step what you wrote and I'm very disappointed tonight...I'll try to find tomorrow what goes wrong with these games and why some work and other ones don't. Regards

**Comment by boufftout** [comment]
Hi creamstick ! According to you, which fba2012 should I take as you wrote that the lastest one wasn't working ? I'm kind of lost with all these files updates. Thanks

**Comment by KMFDManic** [comment]
@boufftout, you a Reddit User?  I can personally help with your setup.

**Comment by boufftout** [comment]
Yes I have just created an account. But if you prefer you could maybe send me a screenshot of the cores and modules you instaled on your hackchi. Thanks and regards.


Envoyé depuis mon smartphone Samsung Galaxy.
-------- Message d'origine --------De : Kyland K <notifications@github.com> Date : 16/11/2017  16:18  (GMT+01:00) À : KMFDManic/NESC-SNESC-Modifications <NESC-SNESC-Modifications@noreply.github.com> Cc : boufftout <romaindespaux@yahoo.fr>, Mention <mention@noreply.github.com> Objet : Re: [KMFDManic/NESC-SNESC-Modifications] Neo Geo roms issues (#32) 
@boufftout, you a Reddit User?  I can personally help with your setup.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/KMFDManic/NESC-SNESC-Modifications","title":"KMFDManic/NESC-SNESC-Modifications","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/KMFDManic/NESC-SNESC-Modifications"}},"updates":{"snippets":[{"icon":"PERSON","message":"@KMFDManic in #32: @boufftout, you a Reddit User?  I can personally help with your setup."}],"action":{"name":"View Issue","url":"https://github.com/KMFDManic/NESC-SNESC-Modifications/issues/32#issuecomment-344954300"}}}

**Comment by KMFDManic** [comment]
@boufftout I edited your comment since it unintentionally posted personal information.  Message me on Reddit, under the name MDFMKanic

**Comment by boufftout** [comment]
Ok sure! Thanks

**Comment by KMFDManic** [comment]
Pulstar works in MAME 2010.  I am now closing this topic, since you should now be fine on running Pulstar:)  I will email you:)
