### ISSUE TITLE
N64 Saves Deleting on System Reset

### ISSUE THREAD

**Issue by timwillhack** [KMFDManic/NESC-SNESC-Modifications#37]
I am wondering if you have tested that your pilotwings sram save maintains itself after you reset your system.  I have tried your hmods and the version in hakchi2.2f cores.  Neither of them keep my saves after I reboot.  Any suggestions?

**Comment by gingerbeardman** [comment]
See #23 hopefully that helps and we can get more info on what that person changed

**Comment by KMFDManic** [comment]
For N64 Saves to properly work, you must have a version of RetroArch from my Core Set installed, along with mupen64plus or glupen.  Using mupen or glupen, with another version of RetroArch, will yield different results.  Games that are TOO large, will only sram save, when uncompressed.  But, a majority of games, including Ocarina of Time, Pilotwings, and so on, work fine with this set-up.  And, you cannot JUST install the RetroArch.  You must also uninstall any previous RetroArch you have had installed.  Otherwise, you will create a conflict.

**Comment by timwillhack** [comment]
Thank you, you are correct it seems to work now after I installed your retroarch version.  I hope you have a great Thanksgiving!
