### ISSUE TITLE
Mame 2017 in latest pack

### ISSUE THREAD

**Issue by creamstick** [KMFDManic/NESC-SNESC-Modifications#38]
The blurb for Mame 2017 in the latest pack has the same blurb as Mame 2003 - is this a new one? Which Mame version does it support (like Mame 2003 is the same as Mame 0.78)?

Cheers!

**Comment by KMFDManic** [comment]
The MAME 2017 was a test file.  Unfortunately, due to it being so large, it is not possible to install on the NESC/SNESC.  It triggers the invalid kernel size perimeter.  I may work more with it, and see about it functioning on USB-HOST, albeit, a different way.  But, for now, it is DOA.  Thanks for the heads up.  It was included, purely by accident:)  You are welcome to send me a message on Reddit @creamstick and we can brainstorm the best way to go about NEO-GEO Stuff:)
