### ISSUE TITLE
[Request] BSX-Satellaview Emulation Core

### ISSUE THREAD

**Issue by atrac17** [KMFDManic/NESC-SNESC-Modifications#4]
I don't know if it's possible, but could you look into a Emulation solution for BSX?

https://bsxproj.superfamicom.org/downloads.htm

**Comment by KMFDManic** [comment]
Just added SNES9x 1.54 to the Core Set.  Some BSX-Satellaview Games previously functioned, just fine, via SNES9x 2010.  This Updated 1.54 should be, pretty much, what you are looking for!  Let me know how it works out!  I also did a Dual Core Variant, so that you can run Standard (Non-Canoe Command Lined) SNES Games, along with SNES9x 2002/2005/2010, if need be.

**Comment by KMFDManic** [comment]
I can confirm that several BSX Games run on the SNES9x Core.  Some will require patching, to get past title screens, such as the F-Zero Grand Prix Games, and a few others!  But, I tested several, and they run!  I will leave this issue temporarily open, til the patching perimeters are figured out!

**Comment by atrac17** [comment]
Thank you so much for updating the SNES9x core to 1.54.1, I'd requested this elsewhere figuring it would work if bsnes wasn't able to be run in RetroArch. All responses to my request we're  there's no reason to update SNES9x. I'll be checking it out in about ten minutes. Please let me know when you figure out the patches for the BS F-Zero Grand Prix games. That's primarily what I'd like to play.

**Comment by blackjack-78** [comment]
Hi dude!
I've installed the latest updates(hakchi2 too...).
I can't run "BS-F-Zero Grand-Prix 2"(in your"cores", snes9x 1.54.1 is named"snes9x_10_19_17" with no numbers...not a problem for me, it's just to be sure because it's the one that i've installed with "your" retroarch...^^).
When i select the game, the screen turning black...and it's stay like that, no more"response"...So i need to shut down the system with the "manual mode"...
By the way, thanks for your work, i really appreciate.

**Comment by KMFDManic** [comment]
@blackjack-78 The SNES9x Cores are set up to run a very specific way on the NESC, and another way on the SNESC.  It may be slightly confusing.  But, bear with me:)  The SNES9x Cores in the Main directory with all of the other Cores, on SNESC, can ONLY run Games when you do the following.  

1.  Have RetroArch installed, obviously!

2.  Command line for the game has to have --retroarch added to the very end!  Like so, 

/bin/clover-canoe-shvc-wr -rom /usr/share/games/CLV-U-XFJBY/Rock_n__Roll_Racing_(USA).sfrom.7z --volume 100 -rollback-snapshot-period 600 --retroarch

Adding this --retroarch perimeter triggers the coding to allow RetroArch to run it.  Whichever SNES9x Core you have installed will be the one that is triggers.  You can only have 1 installed at a time, this way!

Now then, I also set things up a different way, where you can install more than one SNES9x at a time, to Dual Use them (Remember, you can only install 1 at a time, the normal way on SNESC!).  These Dual Use Cores are in the Dependencies & Extras Folder.  These work with Standard SNES, Non-Canoe Command Lined Games.  These are added a few different ways.  I did one video on how to add these, here...

https://www.youtube.com/watch?v=7jrcJZCynFA&t=263s

But, command line for these, once installed, could be like so...

/bin/snes9x /usr/share/games/CLV-Z-SQUJF/Rock_n__Roll_Racing_(USA).7z

Which would trigger the 9x variant of the SNES9x Cores!  You could run more than 1 SNES9x Core this way!  

Finally, if on NESC, the Dual Cores would behave the exact same way as the Standard SNES9x Cores, and could all be dual+ used, since the script to trigger the Canoe Command line would be ignored!

Lastly, BS-F-Zero Grand-Prix 2 will run, but it will not be able to be played, since it needs specially patched to bypass the intro-screen!  But, you can certainly watch an attract mode til the patching gets figured out:)  

Hope this all makes sense!

**Comment by atrac17** [comment]
@KMFDManic I installed the new core, it works wonderful. I also installed your RetroArch core, mgba, and gambatte core. I noticed I can no longer choose a color pallette with gambatte to change how the GB, SGB, and GBC under the options. Is this because of the RetroArch update? I'd prefer to use your core modules solely.

**Comment by blackjack-78** [comment]
A big thanks for the explanations. Like i'm a newbie it makes me learn...a lot. Really!
I'm feeling like your new Padawan (in terms of emulation...)!
I've more than 150 games running on my snes( snes for the most; with retroarch, snes9x and the extreme-filter combined; and some on genesis and MAME...always with your cores), and BS-F-Zero Grand Prix 2 is the"exception". So, i think i'm gonna wait for a patch...
I'm looking forward for your next"releases"(youtube included ^^).
See ya!
A belgian follower.

**Comment by KMFDManic** [comment]
@atrac17, gambatte still works fine:)  Except, you need to use Internal instead of Auto.  Using Internal will give you the palettes you desire to use:)  Very minor differential, and I am glad it isn't broken!  It just needs done with Internal, instead!  Hope that helps:)

@blackjack-78 I will toy around more with the F-Zero Grand Prix Games and keep this issue informed of any changes I discover!

**Comment by blackjack-78** [comment]
Hi dude
While i was watching my snes romset ,i think i've found smomething interesting... Maybe i'm wrong but it can possibily be a way to find the key for runing bsx games: it's the BS-X BIOS.smc, and it can easily find in a snes-romset...Hope this is gonna help...even a little bit ^^.

**Comment by KMFDManic** [comment]
I can happily confirm many BSX-Satellaview Games run just fine:)  Some require patching.  But, F Zero Grand Prix 2 runs quite nicely!  So, use the 9x Core in my set, and you are good to go!  Bios not necessary.
