### ISSUE TITLE
Not a problem - Help Request

### ISSUE THREAD

**Issue by flavioliu** [KMFDManic/NESC-SNESC-Modifications#43]
Guys, sorry for being so dumb, but how do I access the mame "tab menu" on retroarch in snes classic ?

(When on windows pc, when we press tab key, it opens the mame menu, where you can set a input per game and many other settings)

How do I open this mame "tab" menu using retroarch?

Mame version I'm using is Mame2003.

**Comment by gingerbeardman** [comment]
Start + Select

**Comment by flavioliu** [comment]
Gingerbeardman, no, start+select brings up retroarch menu. I am talking about the mame menu. 

[http://www.cincinato.org/snowbros/snow_bros_images/snow_bros_mame_menu1.jpg](http://www.cincinato.org/snowbros/snow_bros_images/snow_bros_mame_menu1.jpg)

**Comment by gingerbeardman** [comment]
In RetroArch you can view the key bindings:

Core > Settings > Input > Input Hotkey Binds > Menu toggle

**Comment by flavioliu** [comment]
Ok, But how do I press R2/L2 on a snes classic gamepad?

**Comment by KMFDManic** [comment]
@flavioliu You need to change R2 to R1, temporarily, in order to access it.

1.  select+start, obviously, to pull up RetroArch Options
2.  Settings
3.  Input
4.  Input User 1 OR 2 Binds
5.  Select the button you want to change, then tap A, then tap the button you want it changed to!
6.  Keep in mind, if your B button is BACK in the RetroArch Options, and you reconfigure it to Y, Y will then become your back button!
7.  Avoid changing select+start, as then you will end up breaking your ability to use RetroArch Options!  And, you will need to uninstall RetroArch, then reinstall it!
8.  If you screw up, simply choose User 1 OR 2 Bind Default ALL!  
9.  Just back out to quick settings, then resume the game, to test things:)
10.  If satisifed with the mapping, leave it alone:)  It should save.  I powered off the system and back on and it worked absolutely perfectly.  
11.  Use Bind Default ALL when you want to revert.  And, do not forget, if you truly screw things up...Just uninstall RetroArch/Reinstall RetroArch:)  

This will help you do the R2 to R1, and back, with relative ease:)

**Comment by flavioliu** [comment]
Thank you KMFDManic. I will test it out once I arrive at home.

**Comment by KMFDManic** [comment]
@flavioliu Given that I have personally tested and can confirm this, I am closing this issue.  But, I still have plans to do an hmod of sorts, to help push config files to the NESC/SNESC, so that this can be done without needing to use RetroArch:)  I just need to figure out which way I would like to proceed.  I am catering to Cores like MAME 2000, most notably!
