### ISSUE TITLE
Save state broken with Retroarch?

### ISSUE THREAD

**Issue by bslenul** [KMFDManic/NESC-SNESC-Modifications#46]
https://youtu.be/9ARHOygu1-E

ActRaiser with Canoe, no problem, ActRaiser 2 with Retroarch (_km_retroarch_12_3_17 and _km_snes9x_11_19_17), the save state almost never work (it worked only once in the video!) :|
I tried with Batman on NES and same thing happened, sometimes it works but most of the time it doesnt :(

I'm using USB-HOST but I don't think that's the problem since it works flawlessly with Canoe. I tried with saves on the console and with the saves on the USB drive, same results.

**EDIT**  
Just tried with Retroarch core from Cluster's retroarch-clover 1.0c and it works perfectly for both SNES (still with _km_snes9x_11_19_17) and NES. And also it's waaaaay faster to get back to the menu!

**Comment by KMFDManic** [comment]
What are your command lines for Batman and ActRaiser 2?

**Comment by bslenul** [comment]
I only installed _km_retroarch_12_3_17 and _km_snes9x_11_19_17, my command lines are:  
>/bin/snes /usr/share/games/CLV-U-WEBRY/ActRaiser_2.sfrom.7z

and  
>/bin/nes /usr/share/games/CLV-H-AVGKE/Batman_-_The_Video_Game.nes.7z

I installed the retroarch from Cluster AFTER I made the video. I'll try the uninstall file from your ADVANCED_USERS folder, I'll tell you the results!

**Comment by KMFDManic** [comment]
Yep, you installed RetroArch on top of another RetroArch.  You have 2 RetroArchs installed at once, which is causing a conflict:)  You will not have this issue if you do the proper uninstall procedure for RetroArch.

I will copy the exact same thing I told the other person:)

Ok, given that you are using the 12-1-17 Official Hakchi...Do this..

Uninstall Kernel on Hakchi2 (No need to flash original!)

make a transfer folder on the flash drive, in hakchi directory, same directory as games name is transfer

In this transfer folder, copy the hmods you want to install, retroarch, etc! You will also want clovercon usb and tiny7z and the madmonkey hmod, and of course font overmount!

Do the process on hakchi1 again, The Seriously Don't You F'ing  Remember Me. Once done, power on with the flash drive, you will get a second splash screen signifying you are installing Cores! RetroArch aside, every other Core is easily uninstallable, just by using THIS video...

https://www.youtube.com/watch?v=r-KQceUWH58

If you want to install any Cores, hence forth, make the transfer folder again, then simply copy the cores! Only if you want to update to a new RetroArch will things get finicky. In that case, you are best doing THIS...

Copy into the transfer folder, the uninstall file I have in Advanced Users Folder, which will uninstall ALL Cores. You will get an immediate shutdown error. But, it is ok! Just make the transfer folder again, and copy the hmods you need, to install, again:) I have done this countless times. It is necessary in your case. Plus, you will learn from it:)

There is another way of uninstalling RetroArch.  But, I will have to make an adjustment to my Core for it to properly work.

**Comment by bslenul** [comment]
Ok so I uninstall every hmods with your `uninstall` file from `\ADVANCED_USERS` then reinstall ONLY those hmods with the `\transfer` folder: https://i.imgur.com/p0FscXq.png

And same thing sadly.

**Comment by KMFDManic** [comment]
For the record, for your Command Lines, they should be this, if using the RetroArch in my set...

/bin/snes /usr/share/games/CLV-U-WEBRY/ActRaiser_2.sfrom.7z

That is a Canoe Rom.  You are way way better off loading it via RetroArch, using my Dual Core Method:)

https://www.youtube.com/watch?v=7jrcJZCynFA&t=50s

You should add it again, as per the above video.  The sfrom, itself, may have issues due to it being a Good Set Rom, etc.

/bin/nes /usr/share/games/CLV-H-AVGKE/Batman_-_The_Video_Game.nes.7z

You will want this to be like this!

/bin/nestopia /usr/share/games/CLV-H-AVGKE/Batman_-_The_Video_Game.nes.7z

OR

/bin/fceumm /usr/share/games/CLV-H-AVGKE/Batman_-_The_Video_Game.nes.7z

Alternately, you can run FCEUMM like this...

/bin/nes /usr/share/games/CLV-H-AVGKE/Batman_-_The_Video_Game.nes.7z --retroarch --fceumm

So, it seems your issue may be directly attributed to your command lines and/or use of Good Set Roms.

Have you tried making a saves folder on flash drive, as well?

**Comment by bslenul** [comment]
I am already using Retroarch for ActRaiser 2 (I even show the RA menu in my video) /bin/snes launches the game with snes9x. And /bin/nes launches the game with FCEUmm, I'll try with /bin/nestopia.

As I said in my first message, I tried saves on the SNESC and on USB drive, got the problem on both cases.

The thing I really don't understand is that I have absolutely no problem when using Cluster's retroarch.

**Comment by bslenul** [comment]
Same thing for Batman with nestopia, the save state loaded correctly the 1st time, the next tries just start the game from the beginning.

**Comment by KMFDManic** [comment]
RetroArch 1.6.7. is truly the only thing I have changed in the last few days.  I tested out both ActRaiser 2 and Batman and haven't had any issues saving.  BUT, I am not using an sfrom for ActRaiser 2, nor is it a Good Set Rom.  Batman saved fine with both FCEUMM & Nestopia, and that is also not a Good Set Rom.  1.6.7 is definitely nice.  But, obviously, if issues are prevalent with saves, due to 1.6.7, then I will revert!  For kicks, try the last variant I had, that didn't have 1.6.7 in it, 

https://ufile.io/o4w1y

I truly appreciate your feedback.  And, if this truly is an issue, I will revert to the last RetroArch I currently used.

**Comment by KMFDManic** [comment]
Link Updated.

**Comment by bslenul** [comment]
Same thing with this file too (on a fresh install) :(

https://youtu.be/H7z15Xwcsz8

If you have 5mn look the video and tell me if I'm doing something wrong (but I'm pretty sure I don't), I show the command lines at the end, I dont know if it will be easy to see on youtube but I changed them to:

>/bin/fceumm /usr/share/games/CLV-H-AVGKE/Batman_-_The_Video_Game.nes.7z

and
>/bin/snes9x /usr/share/games/CLV-U-WEBRY/ActRaiser_2.sfrom.7z

**Comment by KMFDManic** [comment]
What retroarch version is in your options?

**Comment by bslenul** [comment]
I see 1.4.1 with your latest link (_km_retroarch_extreme_filters_11_25_17).

**Comment by KMFDManic** [comment]
Ok, it is starting to seem more and more to be something possibly related to USB-HOST.  Can you try 12-3-17 on normal SNESC, non USB-HOST, if you do not mind?

**Comment by bslenul** [comment]
Sure I can do that, see you in 5~10mn! :D

**Comment by bslenul** [comment]
Same thing without USB-HOST :x

**Comment by KMFDManic** [comment]
One more test for now...Run the games uncompressed, on normal SNESC, and via USB-HOST.

Thanks again!

I will clarify the issue when I am on PC:)

**Comment by bslenul** [comment]
https://youtu.be/v6gS7XMWj8w

I show the games in FTP to prove that I uninstalled USB-HOST, after flashing the custom kernel I installed only _km_retroarch_12_3_17 and _km_snes9x_11_19_17.

1st save state didnt work, 2nd worked, 3rd didnt work :/

**Comment by KMFDManic** [comment]
You try uncompressed?

**Comment by bslenul** [comment]
Sorry didnt see your last message, I'll try uncompressed!

**Comment by bslenul** [comment]
Same thing uncompressed without USB-HOST.

I'll try with USB-HOST tomorrow but I'm pretty sure it'll give the same results sadly :(

Sorry I'm going to bed, already 2:30am here! And thank you for trying to help, really appreciated :)

**Comment by KMFDManic** [comment]
Thanks for doing the tests.  I will explain this entire scenario so that you understand, once I am home in the morning.

**Comment by KMFDManic** [comment]
Ok, got one minute before work, to try to clarify things for you!

In any case, there is a timer that is used in the decompression of games such as N64 and GBA.  In the Official RetroArch, this timer does not play well with games like Ocarina of Time on N64 and Mother 3 on GBA!  I was able to get it to a good median, so that it worked fine with both of those games, as well as similarly sized games.  Other systems are less affected by this timer.  I, myself, have had no save issues.  But, I primarily use No-Intro for all of my stuff.  When you are around tomorrow, we can run a few more tests.  I may alter the timer, based on these tests, to try to find another median to stick at.  But, generally, this timer is not as pertinent, when it comes to uncompressed games.  It seems like you are using Good Set Roms, which are great on PC, etc.  But, on the Mini NES/SNES, they are not as reliable.  Fester's Quest NES, will absolutely freeze and crash, when it gets to the 3d level on Good Set.  On No-Intro it will not.  Tomb Raider GBC has off-colors in Good Set.  But, fine colors in No-Intro.  In any case, most issues people have, tend to be relative to using Good-Set Roms.  Standard Emulators on PC, run those fine!  But, we are in a very non-standard environment:)  We will continue this tomorrow!  Thank you so much for your help in testing.  Hundreds will appreciate this, when I do adjustments to the set, to compensate for such oddities as saves:)

**Comment by bslenul** [comment]
4am and I still cant sleep (╯°□°)╯︵ ┻━┻

I'm also using No-Intro for SNES and NES! Full sets verified with RomCenter and the latest .dat files from http://www.no-intro.org/

**Comment by KMFDManic** [comment]
I, again, appreciate you helping test things.  We will continue this later today.  One thing to note, suspend states are not as reliable if you try to use them too soon.  You will want to make sure you are in game, usually having control of your character.  I have not had a save state fail on me yet.  Only pre-timer change, would some gba suspend states/sram states fail, and some n64 sram saves fail.  We will figure out things, worry not.

**Comment by bslenul** [comment]
Hey! :)

No problem, if I can help to make your hmods even better I'm happy to help!

USB-HOST reinstalled, _km_retroarch_12_3_17 and _km_snes9x_11_19_17 installed, ActRaiser 2 uncompressed, not really a surprise but same problem with save state :(

**Comment by KMFDManic** [comment]
Feel ready to run a few more tests?

**Comment by bslenul** [comment]
Yup, I'm ready!

BTW I made a very interesting find this afternoon, when I use the reset button and not the controller shortcut to make the save state it works every time.

And also, the problem seems to be the saving part, not the loading, because when I have a working save state I can load it 50 times it will load successfully 50 times.

So is it possible that somehow the problem is with the down+select shortcut?

**Comment by KMFDManic** [comment]
Ok, I knew it wasn't an issue on my end, then, as ONLY you and one other person had this issue:)  I am fine with this, though!  I love doing some strict tests to get things going!

Try THIS, install clovercon-usb, then try save states on USB-HOST.

**Comment by bslenul** [comment]
Clovercon-usb is already installed! Without it I cant use the shortcut ;)

**Comment by KMFDManic** [comment]
Ok, well, here are the results:)  I am now closing this.  But, I would greatly appreciate you sending me a message on Reddit, under MDFMKanic!  We will keep in contact, as you will be a very valuable asset for future tests!  Thanks again, man!

Attention: Test results on Save States.  Some have reported issues with saves with gpSP.  I have perfectly found a median to make MGBA and N64 saves function extremely reliably using Suspend States/In Game Sram Saves for GBA, and ONLY In Game Sram Saves for N64.  I cannot fix gpSP saves, without breaking both MGBA and N64!  So, if you decide you want to run gpSP, run it with games that you are not concerned with saving!  /bin/gpsp AND /bin/mgba for Dual Use:)  Lastly, if your shortcut from RetroArch does not properly work with Saves, be sure cloveron or clovercon-usb is installed!  If it still gives issues, simply push reset button ON the NESC/SNESC, as that works with saves, properly, each and every time...given they work to begin with!  Thanks to all who helped me test this!

Attention: Test results on Save States.  Some have reported issues with saves with gpSP.  I have perfectly found a median to make MGBA and N64 saves function extremely reliably using Suspend States/In Game Sram Saves for GBA, and ONLY In Game Sram Saves for N64.  I cannot fix gpSP saves, without breaking both MGBA and N64!  So, if you decide you want to run gpSP, run it with games that you are not concerned with saving!  /bin/gpsp AND /bin/mgba for Dual Use:)  Lastly, if your shortcut from RetroArch does not properly work with Saves, be sure cloveron or clovercon-usb is installed!  If it still gives issues, simply push reset button ON the NESC/SNESC, as that works with saves, properly, each and every time...given they work to begin with!  Thanks to all who helped me test this!
