### ISSUE TITLE
Delay before fast forward begins (but not rewind)

### ISSUE THREAD

**Issue by gingerbeardman** [KMFDManic/NESC-SNESC-Modifications#51]
I have R assigned to fast forward. I use it to speed up animations and cutscenes. 

On SNESC there's a delay of about 1 second before it begins fast forwarding.

With the same setup on 3DS there's no delay. 

I'm testing in PicoDrive

Interestingly, there is no delay with rewind (mapped to L trigger) just fast forward (mapped to R trigger)

**Comment by KMFDManic** [comment]
The different Cores handle timing for Rewind/Fast Forward differently.  Have you tried Fast Forward on Genesis Plus GX?  Example: Rewind for SNES9x2010 hiccups, whereas it runs fine on SNES9x2005. You will not get the same experience as you would on 3DS, nonetheless. RetroArch options can vastly vary in execution, depending on format.

**Comment by gingerbeardman** [comment]
I'll try Genesis Plus. 

It feels like key repeat delay if that makes any sense?

**Comment by KMFDManic** [comment]
Next Update will be RetroArch Upgrade. This may or may not better the delayed timing.

**Comment by gingerbeardman** [comment]
I have two buttons bound to fast forward. The standard bind and my custom bind. How do I go about removing the standard bind?

**Comment by KMFDManic** [comment]
Once you save config and it sticks, best way is to uninstall and reinstall retroarch.  I don't save the binds, so that I revert to default automatically.  I will get a new RetroArch posted today.  It will be experimental and not guaranteed to be fully stable, as of yet.  But, I will also be reposting a fixed 1.6.9, which is working fine for me with every core I have been testing.  So, 1.6.9 may become the stable replacement for 1.6.7, and .1.7 will be experimental til I deem it otherwise.

**Comment by gingerbeardman** [comment]
Can I FTP in and change the binds directly?

**Comment by KMFDManic** [comment]
I will try to make another way available to do binds.  Also, in light of the latest issue, with running Japanese Games, I will look into "fixing" things so Japanese Games run.  Glad you both brought that to my attention.  I hope your Hanafuda Game runs, after all:)

**Comment by KMFDManic** [comment]
@gingerbeardman New RetroArch and New PicoDrive will hit next Update, either today or tomorrow.  If the timing is still off for fast forward on PicoDrive, it is something that we will have to contend with for now.  But, you will have Genesis Plus GX as an alternative.  Hopefully, timing works better for you with the Update I am posting.

**Comment by gingerbeardman** [comment]
PicoDrive is my choice because I run T&E SOFT golf games with CPU=400% which allows me to play a very modern feeling game. I will look into binding only one key to fast forward and see how I get on.

**Comment by gingerbeardman** [comment]
Where am I looking for the key bind settings for PicoDrive? (FTP to SNESC)

**Comment by gingerbeardman** [comment]
No luck here messing with binding settings.

Interestingly, there is no delay with rewind (mapped to L trigger) just fast forward (mapped to R trigger)

**Comment by KMFDManic** [comment]
Others with the same issue on other RetroArch Formats that are not ordinarily supported (unofficially supported), have tended to have a few delay issues with "hot keys".  This seems to be compile based, and a half second delay is not as bad as some of the ones I have seen posted!  Some take 5 seconds!  Since we communicated about this, I am now closing this issue.  Think of it this way!!!  What does Superman do before he launches off into the air?  He crouches down for a half second:)  What does Speedy Gonzales do before he runs off?  He spins his feet in place for a half second:)  This gives you time to be prepared for the fast forward to take effect, especially in more action oriented games:)

**Comment by gingerbeardman** [comment]
All good my friend, comment with the great work and thanks for looking into this for me
