### ISSUE TITLE
[PX68K] spaces in filename cause problems

### ISSUE THREAD

**Issue by gingerbeardman** [KMFDManic/NESC-SNESC-Modifications#62]
I see with all your cores you quote the chosen file when you launch it - great!

however, for some reason in PX68K the filename is truncated at the first space when i open the menu with L2. I have to reselect the disk image through the L2 menu to get it to display in full and be able to boot it.

![ptlotg1n qko](https://user-images.githubusercontent.com/49612/34798266-4563a768-f653-11e7-9783-4ed2f44fdc95.png)

**Comment by KMFDManic** [comment]
I would post this as a request on the github.  But, for now, do titles, like this AkumajouDracula, etc  Just use Caps to easily separate.  Special characters are also an annoyance for USB-HOST, as you are already aware:)  Once they look into a possible fix, I will compile it.  Otherwise, the Caps method is working perfectly for me:)
