### ISSUE TITLE
[Suggestion] Add your cores to RetroArch buildbot?

### ISSUE THREAD

**Issue by gingerbeardman** [KMFDManic/NESC-SNESC-Modifications#7]
Would be great to make these official?

**Comment by KMFDManic** [comment]
This is not necessary, as the Source Files I use come from Libretro, which buildbot also uses.  So, it is completely unnecessary:)  There are some variances.  But, things would be far too convoluted if I tried keeping these up to date in more than one place!  Thanks for your suggestion, however!  Madmonkey and Cluster recommended I stick to github, as things would work out best, in this platform!  For now, I would love to just get more Cores running, and optimize things!

**Comment by gingerbeardman** [comment]
The only reason I ask is that, for example, the cores you are generating are using more recent code than the cores that are being built for Nintendo 3DS. 

To ask another way, what's the best way to get updated cores like yours on that system?

**Comment by KMFDManic** [comment]
I can try to help with custom cores for your 3DS.  I do not have to be tethered to just the Mini NES/SNES.

**Comment by gingerbeardman** [comment]
Awesome. Let's see after hakchi 2.5

**Comment by gingerbeardman** [comment]
Sounds like they want to do what you've already done?

https://www.libretro.com/index.php/retroarch-roadmap-for-v1-7-0-and-beyond/

**Comment by KMFDManic** [comment]
@gingerbeardman I am in pretty close contact with madmonkey, and several other great People who can make RetroArch a better and more optimal thing.  Just you wait til you see some of the upcoming things that will be able to be done:)  Even in my next Update, you will be able to have limited support for Light Gun Games:)  That will be in the NEXT update, later today:)  I will get a video posted, too, of course!  But, some of the other nifty surprises, will truly stand out as awesome!  Running MP3s is now possible, And, next up, in due time...will be videos:)  That is just ONE of several things to look forward to:)  I hope you get the chance to get the proper OTG Cable, so that you can jump onto using USB-HOST:)

**Comment by gingerbeardman** [comment]
Woohoo!

**Comment by gingerbeardman** [comment]
Keyboard support for MSX/X68K/etc should be amazing. Bluetooth would be the dream, so I can use my Nintendo DS Bluetooth keyboard!

**Comment by gingerbeardman** [comment]
> I hope you get the chance to get the proper OTG Cable, so that you can jump onto using USB-HOST:)

My [OTG cable](http://www.ebay.co.uk/itm/201892169826) arrived, but now I see that you say "the proper OTG cable"... which one is that?

**Comment by KMFDManic** [comment]
@gingerbeardman There is a decent chance that one will work.  I made available everything you need to do the process in my Core Set, thanks to madmonkey.  Plus, a few of my videos help with things.  It won't hurt to try!  Just keep things simple, and let me know if you need any personal assistance.
