### ISSUE TITLE
_km_retroarch_167_1_23_18  and _km_retroarch_170_1_23_18

### ISSUE THREAD

**Issue by bbaggins19** [KMFDManic/NESC-SNESC-Modifications#72]
I am not running USB host, and both of the above listed hdmods will not play any nes games on the snes classic edition.  Instead, I had to use   _km_retroarch_170_1_14_18, which does allow me to play nes games on the snes classic.  Can you please updated the above listed hmods?  Thanks for your assistance and great work!

**Comment by 2skoops** [comment]
I also had problems with them last night (installed on a SNESC not using USB host).  After uninstalling old cores, I installed retroarch, snes9x, and nxengine.  Both Cave Story and any SNES games would show a black screen for a few seconds before going back to the menu (no error reported).
This was my first time trying to use your _km versions of the cores, so I ended up just going back to my old cores and everything was fine.  I didn't try using older versions of the _km cores.

**Comment by KMFDManic** [comment]
@bbaggins19 @2skoops 

ATTENTION:  It has been brought to my attention that some are having issues running NES/SNES with the new Update.  So, here is a hotfix, for now.  Replace the RetroArchs in the last Update with THESE.  Note: Special Characters will not work with these Hotfix Replacements.  But, a fix will be accounted for as soon as possible.  Sorry for any inconvenience.   https://ufile.io/6p7fi

**Comment by KMFDManic** [comment]
@bbaggins19 @2skoops Problem solved:)

ATTENTION:)  In order to use the NEW RetroArchs in my Core Set from 1-24-18,
you will need to take the included remote-exec file and OVERWRITE
the current one in your hakchi2 directory.

1.  Control+F

2.  Search for remote exec

3.  Open Containing Directory

4.  Let included one overwrite it

**Then, for anyone with issues running NES/SNES should be back in 
action!  And, of course, Special Characters will work for USB-HOST!

Directory the remote-exec is in..

hakchi2/mods/mod_hakchi/hakchi/rootfs/bin

Personal thanks to Madmonkey for helping fix this:)

Sincerely, KMFDManic...  Sorry for any inconvenience.  https://ufile.io/dhacs

**Comment by bbaggins19** [comment]
Ok, thank you for all of this awesomeness!!  Rock on!!
