### ISSUE TITLE
[PX68K] starts to black screen if there's a space in rom file name

### ISSUE THREAD

**Issue by gingerbeardman** [KMFDManic/NESC-SNESC-Modifications#78]
Running X68 games I am getting varying results. 

Often it starts to a black screen and I have to power cycle the SNESC.

Took a bunch of testing to figure out it was because of spaces in file names!

What works (at least, my testing was not exhaustive):
- raw floppy disk images (I've tried XDF, DIM, D88; or xdf, dim, d88)
- as .7z or .zip files (though archives are impractical for multi disc games, see #77)

What does not work:
- any file with a space in it

**Comment by KMFDManic** [comment]
This has always been an issue for mounting of discs, for many years:)  Even when using virtual drives or chdman, the moment you introduce spaces into file names, improper mounting and/or errors tend to occur.  This is generally offset by simplifying file names and/or using acceptable characters.  Sonic CD.iso is better as SonicCD.iso  I usually do this, as example, to bypass this formatting...SonicTheHedgehog.iso  Capitalize where spaces would typically be, in order to still keep things neat and tidy.

**Comment by gingerbeardman** [comment]
Interesting! I've not from into the issue on any other platforms. I'll look into it

**Comment by KMFDManic** [comment]
Yes, this has been something that I have always pushed people towards, over the years.  Look for yourself:)  Any ISO you download, is nearly always named in such a way that it either has Zero Space or underscores instead of spaces:)  This is something I dealt with in the early days of AlcoholSoft, Daemon Tools, etc::)  Even though there are some technical ways around it, many programs trip over spaces, so I tend to recommend the proper etiquette as far as naming, to avoid such potential issues:)

**Comment by KMFDManic** [comment]
Get your coding changed pull requested Upstream:)  Looking forward to seeing things implemented:)
