### ISSUE TITLE
VICE-plugin: Two player support is still missing

### ISSUE THREAD

**Issue by hoderer** [KMFDManic/NESC-SNESC-Modifications#88]
Hey @KMFDManic, great that you're still around. Do you need to sleep at all? :)

I took a little break and now I'm back again and I'm glad, that you still update the modules. Great job!!! I know not many people are using the VICE-plugin, but I would be happy if there could be 2 player support one day. There were some updates, but still no two player support.

Could you look into it once again or am I missing something and it's already implemented!?

PS: Really looking forward to N64 with SNESC-controller support. I tried it myself, but there were always side-effects.

PPS: Did you check out the new 2017 C64-game "Sam's Journey"? This is just mind blowing and surely one of the best games of all time for this machine!

**Comment by gingerbeardman** [comment]
See: https://github.com/libretro/vice-libretro/issues/10

**Comment by KMFDManic** [comment]
@hoderer Looking further into it.  Commodore 64 was originally set up to use just 1 Joystick.  This was generally in port 2, along with keyboard in port 1.  Using Joystick in Port 1 would usually cause conflicts with the Command Line interface.  To truly use 2 Joysticks, you would need a 4 Player Interface Adapter plugged into the Back User Port.  This would keep things entirely separate from the Keyboard in Port 1 and Joystick in Port 2, since they would use different communication protocol.  Essentially, it was an early Serial Port.  I used this type of thing to connect 2 computers together for direct links in the past.  So, basically, think trying to plug in 4 controllers into your SNESC's 2 Ports:)  Not so easy, is it:)  It would require special configuration and set-up to Map keyset A to Controller one and keyset B to Controller two, so that there are no shared conflicts with the keyboard!  We can both toy with the idea and see about proper configuration.  But, since you've been gone, this should make things easier!

https://www.youtube.com/watch?v=91XA_0xfN_U&t=65s

And, of course, the Adapter I mentioned!

 https://www.c64-wiki.com/wiki/4_Player_Interface

I believe it can be done.  But, it will require a little testing with the mapper and various combinations of Options for Controller 1/2

**Comment by gingerbeardman** [comment]
More info on the two control ports: https://www.c64-wiki.com/wiki/Control_Port

**Comment by hoderer** [comment]
thanks for making that clear, so it's working more or less as planed at the moment. I was wondering the whole time, why they didn't implement two joysticks and had absolutely no idea. If you take a look into it some day and need a tester - you can always count on me, but no rush. Whenever you find the time. thanks again!

**Comment by gingerbeardman** [comment]
Apparently it's possible: https://retropie.org.uk/forum/topic/5838/c64-vice-is-it-possible-to-use-two-joysticks/5

**Comment by hoderer** [comment]
cool, thanks for the research!!!

**Comment by KMFDManic** [comment]
@gingerbeardman I knew it was theoretically possible:)  We just have to be minor masochists to achieve results without conflict:)  At least it isn't as bad as someone wanting to run N64 on NESC controller!  Yes, that has been asked, before!  But, I did get N64 running with SNESC controller:)  Still finalizing the set-up for that!

@hoderer Main thing is, patience and testing will go a long way with this one.  Things will not work just like on PC.  Many things I have achieved on NESC/SNESC have been done by thinking outside the box.  Even though the coding is there on PC, doesn't mean it will work on NESC/SNESC.  Example, Irem Encryption, while in the code for MAME 2003, is completely broken for us!  Hence, my In the Hunt Videos for PS1 on YouTube!  They are a riot:)

**Comment by hoderer** [comment]
N64 on NESC controller is... quite... argh!!! people are crazy sometimes :)

glad you got it working with SNESC controllers - can't wait to try it out!

yes I know it's a long way wth the VICE core, that's why I wrote "no rush" and stuff like that. It's a bless that people like you are working hard on the cores, having patience is the least we users can do...

**Comment by KMFDManic** [comment]
@hoderer The mapping was the biggest thing.  The entire reason Mapping is now possible on RetroArch, all stems from my originally doing C64 for the Mini NESC:)  It was immediately noticeable that mapping would be necessary.  fr500 helped make that happen.  And, now, as a result, the Mini NES/SNES is far superior, since even Dosbox works with it:)  Literally most of the PC Cores I added, can be keyboard mapped to controllers now.  This is pretty awesome.

**Comment by gingerbeardman** [comment]
I had set a bounty on libretro mapping, and it languished for so long that I reclaimed it. And then NESC came out and these cores and the rest is history!

**Comment by hoderer** [comment]
Great achievement of you two! This is exactly the kind of people that this wonderful scene needs! I really hope it's staying alive for a long time... In 2019 there will be most likely a N64 mini, but I'm sure that when it comes to the point most SNESC (mod-)users won't buy one, because by then it's already possible to run N64 games in a very decent way on the SNESC! :)

**Comment by KMFDManic** [comment]
@hoderer I wouldn't expect much from an N64 Mini.  Just like with Pilotwings not being on SNESC, I see them really being selective on any and all games they add.  We may potentially have better support, right now, for all we know:)  Many games are quite playable.  And, with the recent Bypass Trick I showcased on YouTube, plus a few tweaks, crashing is less frequent.  Hopefully, if they do Mini N64, they have more than just Mario Kart and Mario 64!  They likely will not have Pilotwings 64, though!  I see that being a definitely problem graphic plugin wise!  And, of course, Golden Eye is completely out!  So, all in all, if you seriously looked at licensing, we really don't have much of an amazing line-up to go by!  Being Paper Mario has issues, too, I don't see that happening.  I would say, N64 Games that have been on Virtual Console, are our best bets.

**Comment by gingerbeardman** [comment]
The libretro guys figured out the long-standing Pilotwings 64 "shadow" issue a while back. I think we'll see a GB/GBA Classic - with Tetris and Pokemon and more - before we see N64 Classic.

**Comment by hoderer** [comment]
Good conversation with great infos and thoughts. THANKS!

Yeah, we won't see "Goldeneye 64" and the suprisingly great "new beetle adventure racing" on a N64 mini due to licensing issues... a GBA mini wasn't on my mind, but could be. I guess they'll put some GB-games on it, too (like "tetris" & "super mario land" as kind of a system-seller like back in the days).

**Comment by KMFDManic** [comment]
The best way to go about this would be making a Core Request on the main Github for Vice x64 for multi controller support.  As it stands, it absolutely conflicts with our current set-up.  The 2nd controller is meant to be used for keyboard or for the main controller.  On a real C64, 2 player and on games were run using the Multi-Adapter.  I got 2nd player working on PC, with reconfiguration of the controls.  But, if you attempted to change that here, you'd potentially screw up other Cores.  Player 2 is absolutely disabled on keyboard for ALL Cores, due to keyboard conflicts.  It is tethered entirely to controller.  I never even knew about the multi adapter til you reposted:)  That is the sad thing, many Computers are geared more towards 1 controller at a time!

**Comment by KMFDManic** [comment]
@hoderer You "should" be able to play with 2 players now.  I didn't fully test it!  But, 4 player adapter is a selectable option in most recent Core Update for Vice:)

**Comment by hoderer** [comment]
Great News, Kyland!  Thanks for remembering! I'm gonna test it tomorrow! Things are getting better and better - thanks for your work!!!
