### ISSUE TITLE
[Request] SNES unlimited Sprites and Overclock

### ISSUE THREAD

**Issue by Jord4n** [KMFDManic/NESC-SNESC-Modifications#9]
Hi,

Would like to request unlimited Sprites and Overclock feature like most other cores have for the SNES.  Seems like only SNES is missing this feature for all the 8/16-bit consoles for some reason?

Cheers,
Jord4n

**Comment by KMFDManic** [comment]
I am gonna try to add an enhanced port of 9x to help with overclocking.  Are there any specific games you are trying to run?

**Comment by Jord4n** [comment]
Hey KMFDManic,

That is awesome!  No problems running any games, just think its a shame that us old school gamers still have to suffer sprite flicker and slowdown when most other systems seem to have a solution is all :)

Just wondering why the SNES seems to be the only system without and unlimited sprite or overclock feature like most other systems is all.   Thank you for looking into this!

-J

**Comment by KMFDManic** [comment]
It appears this is a trivial thing that has affected SNES Emulators for quite some time.  There are a few speed hacks that are employed in the various emulators to try to optimize how well games run.  Unfortunately, doing something such as an unlimited sprites, would not fare well.  Overclocking the actual CPU leads to timing issues, and of course minor to severe graphical issues!  

But, there are a few things you can do to speed things up.

RetroArch Wise

1.  In SNES9x that I just posted, have Super FX Overclock set to ONLY 20mhz.  That is closer to the standard that real Super FX ran at.  

2.  Video Settings - Disable Vsynch

3.  Audio Settings (This will cause audio skipping due to the increased speed) - disable Audio Synch

Be sure to remember to change these settings back!  Or, use Save Core/Save Game Override to effectively be permissive to only that Core/Game.  Note, Save Core/Save Game Override works in many instances.  But, not all!

Now, then...

CANOE WISE, if on SNESC, that is!...

You can add this to end of command line

-boost-fx 2

So, unfortunately, it is what it is.  But, hope these alternative methods help.  

Note: Disabling Audio Synch is absolutely hilarious for farming in games!

I do it in THIS video:)

https://www.youtube.com/watch?v=9VcKQqEpTWY&t=7s
