### ISSUE TITLE
Black screen after adding retroarch and extra mods

### ISSUE THREAD

**Issue by Stone2k18** [KMFDManic/NESC-SNESC-Modifications#96]
I dumped the kernel and flashed the custom kernel added 75 games (genesis, nes, sms, gba) added the mods plus the retro arch synced it all. I turn it on. All I get is a black screen. I uninstalled everything and reflashed the original kernal back to factory settings. Started over. I got the same thing. So I added just Snes games.  Works fine.  Added games without the retroarch and mods.  All games show up.  Doesnt play.  What in the hell is going on??? Get back to me appreciate it

**Comment by Stone2k18** [comment]
You have any links I can use.  I just uninstalled everything.  I wanna start from scratch.

**Comment by KMFDManic** [comment]
Which Hakchi are you using?

**Comment by KMFDManic** [comment]
https://github.com/KMFDManic/NESC-SNESC-Modifications/releases
Install Hakchi2 CE from the link
Uninstall Kernel, Flash Custom Kernel, Copy and paste HMODS from the 7z archive into user mods folder.  install RetroArch 1.71, and whichever other HMODS you plan on using 

Refer to COMMANDS folder in Xtras Folder for appropriate Command Line Arguments.  

Closing the issue, since this is entirely a conflict related to User End.  Feel free to respond if you still need help:)
